package org.zikula.modulestudio.generator.cartridges.zclassic.smallstuff.documents;

import de.guite.modulestudio.metamodel.Application;
import org.eclipse.xtend2.lib.StringConcatenation;

@SuppressWarnings("all")
public class License_GPL {
  public CharSequence generate(final Application it) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("                    ");
    _builder.append("GNU GENERAL PUBLIC LICENSE");
    _builder.newLine();
    _builder.append("                       ");
    _builder.append("Version 3, 29 June 2007");
    _builder.newLine();
    _builder.newLine();
    _builder.append(" ");
    _builder.append("Copyright (C) 2007 Free Software Foundation, Inc. <http://fsf.org/>");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("Everyone is permitted to copy and distribute verbatim copies");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("of this license document, but changing it is not allowed.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("                            ");
    _builder.append("Preamble");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("The GNU General Public License is a free, copyleft license for");
    _builder.newLine();
    _builder.append("software and other kinds of works.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("The licenses for most software and other practical works are designed");
    _builder.newLine();
    _builder.append("to take away your freedom to share and change the works.  By contrast,");
    _builder.newLine();
    _builder.append("the GNU General Public License is intended to guarantee your freedom to");
    _builder.newLine();
    _builder.append("share and change all versions of a program--to make sure it remains free");
    _builder.newLine();
    _builder.append("software for all its users.  We, the Free Software Foundation, use the");
    _builder.newLine();
    _builder.append("GNU General Public License for most of our software; it applies also to");
    _builder.newLine();
    _builder.append("any other work released this way by its authors.  You can apply it to");
    _builder.newLine();
    _builder.append("your programs, too.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("When we speak of free software, we are referring to freedom, not");
    _builder.newLine();
    _builder.append("price.  Our General Public Licenses are designed to make sure that you");
    _builder.newLine();
    _builder.append("have the freedom to distribute copies of free software (and charge for");
    _builder.newLine();
    _builder.append("them if you wish), that you receive source code or can get it if you");
    _builder.newLine();
    _builder.append("want it, that you can change the software or use pieces of it in new");
    _builder.newLine();
    _builder.append("free programs, and that you know you can do these things.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("To protect your rights, we need to prevent others from denying you");
    _builder.newLine();
    _builder.append("these rights or asking you to surrender the rights.  Therefore, you have");
    _builder.newLine();
    _builder.append("certain responsibilities if you distribute copies of the software, or if");
    _builder.newLine();
    _builder.append("you modify it: responsibilities to respect the freedom of others.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("For example, if you distribute copies of such a program, whether");
    _builder.newLine();
    _builder.append("gratis or for a fee, you must pass on to the recipients the same");
    _builder.newLine();
    _builder.append("freedoms that you received.  You must make sure that they, too, receive");
    _builder.newLine();
    _builder.append("or can get the source code.  And you must show them these terms so they");
    _builder.newLine();
    _builder.append("know their rights.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("Developers that use the GNU GPL protect your rights with two steps:");
    _builder.newLine();
    _builder.append("(1) assert copyright on the software, and (2) offer you this License");
    _builder.newLine();
    _builder.append("giving you legal permission to copy, distribute and/or modify it.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("For the developers\' and authors\' protection, the GPL clearly explains");
    _builder.newLine();
    _builder.append("that there is no warranty for this free software.  For both users\' and");
    _builder.newLine();
    _builder.append("authors\' sake, the GPL requires that modified versions be marked as");
    _builder.newLine();
    _builder.append("changed, so that their problems will not be attributed erroneously to");
    _builder.newLine();
    _builder.append("authors of previous versions.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("Some devices are designed to deny users access to install or run");
    _builder.newLine();
    _builder.append("modified versions of the software inside them, although the manufacturer");
    _builder.newLine();
    _builder.append("can do so.  This is fundamentally incompatible with the aim of");
    _builder.newLine();
    _builder.append("protecting users\' freedom to change the software.  The systematic");
    _builder.newLine();
    _builder.append("pattern of such abuse occurs in the area of products for individuals to");
    _builder.newLine();
    _builder.append("use, which is precisely where it is most unacceptable.  Therefore, we");
    _builder.newLine();
    _builder.append("have designed this version of the GPL to prohibit the practice for those");
    _builder.newLine();
    _builder.append("products.  If such problems arise substantially in other domains, we");
    _builder.newLine();
    _builder.append("stand ready to extend this provision to those domains in future versions");
    _builder.newLine();
    _builder.append("of the GPL, as needed to protect the freedom of users.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("Finally, every program is threatened constantly by software patents.");
    _builder.newLine();
    _builder.append("States should not allow patents to restrict development and use of");
    _builder.newLine();
    _builder.append("software on general-purpose computers, but in those that do, we wish to");
    _builder.newLine();
    _builder.append("avoid the special danger that patents applied to a free program could");
    _builder.newLine();
    _builder.append("make it effectively proprietary.  To prevent this, the GPL assures that");
    _builder.newLine();
    _builder.append("patents cannot be used to render the program non-free.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("The precise terms and conditions for copying, distribution and");
    _builder.newLine();
    _builder.append("modification follow.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("                       ");
    _builder.append("TERMS AND CONDITIONS");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("0. Definitions.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("\"This License\" refers to version 3 of the GNU General Public License.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("\"Copyright\" also means copyright-like laws that apply to other kinds of");
    _builder.newLine();
    _builder.append("works, such as semiconductor masks.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("\"The Program\" refers to any copyrightable work licensed under this");
    _builder.newLine();
    _builder.append("License.  Each licensee is addressed as \"you\".  \"Licensees\" and");
    _builder.newLine();
    _builder.append("\"recipients\" may be individuals or organizations.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("To \"modify\" a work means to copy from or adapt all or part of the work");
    _builder.newLine();
    _builder.append("in a fashion requiring copyright permission, other than the making of an");
    _builder.newLine();
    _builder.append("exact copy.  The resulting work is called a \"modified version\" of the");
    _builder.newLine();
    _builder.append("earlier work or a work \"based on\" the earlier work.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("A \"covered work\" means either the unmodified Program or a work based");
    _builder.newLine();
    _builder.append("on the Program.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("To \"propagate\" a work means to do anything with it that, without");
    _builder.newLine();
    _builder.append("permission, would make you directly or secondarily liable for");
    _builder.newLine();
    _builder.append("infringement under applicable copyright law, except executing it on a");
    _builder.newLine();
    _builder.append("computer or modifying a private copy.  Propagation includes copying,");
    _builder.newLine();
    _builder.append("distribution (with or without modification), making available to the");
    _builder.newLine();
    _builder.append("public, and in some countries other activities as well.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("To \"convey\" a work means any kind of propagation that enables other");
    _builder.newLine();
    _builder.append("parties to make or receive copies.  Mere interaction with a user through");
    _builder.newLine();
    _builder.append("a computer network, with no transfer of a copy, is not conveying.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("An interactive user interface displays \"Appropriate Legal Notices\"");
    _builder.newLine();
    _builder.append("to the extent that it includes a convenient and prominently visible");
    _builder.newLine();
    _builder.append("feature that (1) displays an appropriate copyright notice, and (2)");
    _builder.newLine();
    _builder.append("tells the user that there is no warranty for the work (except to the");
    _builder.newLine();
    _builder.append("extent that warranties are provided), that licensees may convey the");
    _builder.newLine();
    _builder.append("work under this License, and how to view a copy of this License.  If");
    _builder.newLine();
    _builder.append("the interface presents a list of user commands or options, such as a");
    _builder.newLine();
    _builder.append("menu, a prominent item in the list meets this criterion.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("1. Source Code.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("The \"source code\" for a work means the preferred form of the work");
    _builder.newLine();
    _builder.append("for making modifications to it.  \"Object code\" means any non-source");
    _builder.newLine();
    _builder.append("form of a work.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("A \"Standard Interface\" means an interface that either is an official");
    _builder.newLine();
    _builder.append("standard defined by a recognized standards body, or, in the case of");
    _builder.newLine();
    _builder.append("interfaces specified for a particular programming language, one that");
    _builder.newLine();
    _builder.append("is widely used among developers working in that language.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("The \"System Libraries\" of an executable work include anything, other");
    _builder.newLine();
    _builder.append("than the work as a whole, that (a) is included in the normal form of");
    _builder.newLine();
    _builder.append("packaging a Major Component, but which is not part of that Major");
    _builder.newLine();
    _builder.append("Component, and (b) serves only to enable use of the work with that");
    _builder.newLine();
    _builder.append("Major Component, or to implement a Standard Interface for which an");
    _builder.newLine();
    _builder.append("implementation is available to the public in source code form.  A");
    _builder.newLine();
    _builder.append("\"Major Component\", in this context, means a major essential component");
    _builder.newLine();
    _builder.append("(kernel, window system, and so on) of the specific operating system");
    _builder.newLine();
    _builder.append("(if any) on which the executable work runs, or a compiler used to");
    _builder.newLine();
    _builder.append("produce the work, or an object code interpreter used to run it.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("The \"Corresponding Source\" for a work in object code form means all");
    _builder.newLine();
    _builder.append("the source code needed to generate, install, and (for an executable");
    _builder.newLine();
    _builder.append("work) run the object code and to modify the work, including scripts to");
    _builder.newLine();
    _builder.append("control those activities.  However, it does not include the work\'s");
    _builder.newLine();
    _builder.append("System Libraries, or general-purpose tools or generally available free");
    _builder.newLine();
    _builder.append("programs which are used unmodified in performing those activities but");
    _builder.newLine();
    _builder.append("which are not part of the work.  For example, Corresponding Source");
    _builder.newLine();
    _builder.append("includes interface definition files associated with source files for");
    _builder.newLine();
    _builder.append("the work, and the source code for shared libraries and dynamically");
    _builder.newLine();
    _builder.append("linked subprograms that the work is specifically designed to require,");
    _builder.newLine();
    _builder.append("such as by intimate data communication or control flow between those");
    _builder.newLine();
    _builder.append("subprograms and other parts of the work.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("The Corresponding Source need not include anything that users");
    _builder.newLine();
    _builder.append("can regenerate automatically from other parts of the Corresponding");
    _builder.newLine();
    _builder.append("Source.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("The Corresponding Source for a work in source code form is that");
    _builder.newLine();
    _builder.append("same work.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("2. Basic Permissions.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("All rights granted under this License are granted for the term of");
    _builder.newLine();
    _builder.append("copyright on the Program, and are irrevocable provided the stated");
    _builder.newLine();
    _builder.append("conditions are met.  This License explicitly affirms your unlimited");
    _builder.newLine();
    _builder.append("permission to run the unmodified Program.  The output from running a");
    _builder.newLine();
    _builder.append("covered work is covered by this License only if the output, given its");
    _builder.newLine();
    _builder.append("content, constitutes a covered work.  This License acknowledges your");
    _builder.newLine();
    _builder.append("rights of fair use or other equivalent, as provided by copyright law.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("You may make, run and propagate covered works that you do not");
    _builder.newLine();
    _builder.append("convey, without conditions so long as your license otherwise remains");
    _builder.newLine();
    _builder.append("in force.  You may convey covered works to others for the sole purpose");
    _builder.newLine();
    _builder.append("of having them make modifications exclusively for you, or provide you");
    _builder.newLine();
    _builder.append("with facilities for running those works, provided that you comply with");
    _builder.newLine();
    _builder.append("the terms of this License in conveying all material for which you do");
    _builder.newLine();
    _builder.append("not control copyright.  Those thus making or running the covered works");
    _builder.newLine();
    _builder.append("for you must do so exclusively on your behalf, under your direction");
    _builder.newLine();
    _builder.append("and control, on terms that prohibit them from making any copies of");
    _builder.newLine();
    _builder.append("your copyrighted material outside their relationship with you.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("Conveying under any other circumstances is permitted solely under");
    _builder.newLine();
    _builder.append("the conditions stated below.  Sublicensing is not allowed; section 10");
    _builder.newLine();
    _builder.append("makes it unnecessary.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("3. Protecting Users\' Legal Rights From Anti-Circumvention Law.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("No covered work shall be deemed part of an effective technological");
    _builder.newLine();
    _builder.append("measure under any applicable law fulfilling obligations under article");
    _builder.newLine();
    _builder.append("11 of the WIPO copyright treaty adopted on 20 December 1996, or");
    _builder.newLine();
    _builder.append("similar laws prohibiting or restricting circumvention of such");
    _builder.newLine();
    _builder.append("measures.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("When you convey a covered work, you waive any legal power to forbid");
    _builder.newLine();
    _builder.append("circumvention of technological measures to the extent such circumvention");
    _builder.newLine();
    _builder.append("is effected by exercising rights under this License with respect to");
    _builder.newLine();
    _builder.append("the covered work, and you disclaim any intention to limit operation or");
    _builder.newLine();
    _builder.append("modification of the work as a means of enforcing, against the work\'s");
    _builder.newLine();
    _builder.append("users, your or third parties\' legal rights to forbid circumvention of");
    _builder.newLine();
    _builder.append("technological measures.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("4. Conveying Verbatim Copies.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("You may convey verbatim copies of the Program\'s source code as you");
    _builder.newLine();
    _builder.append("receive it, in any medium, provided that you conspicuously and");
    _builder.newLine();
    _builder.append("appropriately publish on each copy an appropriate copyright notice;");
    _builder.newLine();
    _builder.append("keep intact all notices stating that this License and any");
    _builder.newLine();
    _builder.append("non-permissive terms added in accord with section 7 apply to the code;");
    _builder.newLine();
    _builder.append("keep intact all notices of the absence of any warranty; and give all");
    _builder.newLine();
    _builder.append("recipients a copy of this License along with the Program.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("You may charge any price or no price for each copy that you convey,");
    _builder.newLine();
    _builder.append("and you may offer support or warranty protection for a fee.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("5. Conveying Modified Source Versions.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("You may convey a work based on the Program, or the modifications to");
    _builder.newLine();
    _builder.append("produce it from the Program, in the form of source code under the");
    _builder.newLine();
    _builder.append("terms of section 4, provided that you also meet all of these conditions:");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("a) The work must carry prominent notices stating that you modified");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("it, and giving a relevant date.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("b) The work must carry prominent notices stating that it is");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("released under this License and any conditions added under section");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("7.  This requirement modifies the requirement in section 4 to");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("\"keep intact all notices\".");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("c) You must license the entire work, as a whole, under this");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("License to anyone who comes into possession of a copy.  This");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("License will therefore apply, along with any applicable section 7");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("additional terms, to the whole of the work, and all its parts,");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("regardless of how they are packaged.  This License gives no");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("permission to license the work in any other way, but it does not");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("invalidate such permission if you have separately received it.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("d) If the work has interactive user interfaces, each must display");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("Appropriate Legal Notices; however, if the Program has interactive");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("interfaces that do not display Appropriate Legal Notices, your");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("work need not make them do so.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("A compilation of a covered work with other separate and independent");
    _builder.newLine();
    _builder.append("works, which are not by their nature extensions of the covered work,");
    _builder.newLine();
    _builder.append("and which are not combined with it such as to form a larger program,");
    _builder.newLine();
    _builder.append("in or on a volume of a storage or distribution medium, is called an");
    _builder.newLine();
    _builder.append("\"aggregate\" if the compilation and its resulting copyright are not");
    _builder.newLine();
    _builder.append("used to limit the access or legal rights of the compilation\'s users");
    _builder.newLine();
    _builder.append("beyond what the individual works permit.  Inclusion of a covered work");
    _builder.newLine();
    _builder.append("in an aggregate does not cause this License to apply to the other");
    _builder.newLine();
    _builder.append("parts of the aggregate.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("6. Conveying Non-Source Forms.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("You may convey a covered work in object code form under the terms");
    _builder.newLine();
    _builder.append("of sections 4 and 5, provided that you also convey the");
    _builder.newLine();
    _builder.append("machine-readable Corresponding Source under the terms of this License,");
    _builder.newLine();
    _builder.append("in one of these ways:");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("a) Convey the object code in, or embodied in, a physical product");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("(including a physical distribution medium), accompanied by the");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("Corresponding Source fixed on a durable physical medium");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("customarily used for software interchange.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("b) Convey the object code in, or embodied in, a physical product");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("(including a physical distribution medium), accompanied by a");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("written offer, valid for at least three years and valid for as");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("long as you offer spare parts or customer support for that product");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("model, to give anyone who possesses the object code either (1) a");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("copy of the Corresponding Source for all the software in the");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("product that is covered by this License, on a durable physical");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("medium customarily used for software interchange, for a price no");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("more than your reasonable cost of physically performing this");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("conveying of source, or (2) access to copy the");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("Corresponding Source from a network server at no charge.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("c) Convey individual copies of the object code with a copy of the");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("written offer to provide the Corresponding Source.  This");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("alternative is allowed only occasionally and noncommercially, and");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("only if you received the object code with such an offer, in accord");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("with subsection 6b.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("d) Convey the object code by offering access from a designated");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("place (gratis or for a charge), and offer equivalent access to the");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("Corresponding Source in the same way through the same place at no");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("further charge.  You need not require recipients to copy the");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("Corresponding Source along with the object code.  If the place to");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("copy the object code is a network server, the Corresponding Source");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("may be on a different server (operated by you or a third party)");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("that supports equivalent copying facilities, provided you maintain");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("clear directions next to the object code saying where to find the");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("Corresponding Source.  Regardless of what server hosts the");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("Corresponding Source, you remain obligated to ensure that it is");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("available for as long as needed to satisfy these requirements.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("e) Convey the object code using peer-to-peer transmission, provided");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("you inform other peers where the object code and Corresponding");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("Source of the work are being offered to the general public at no");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("charge under subsection 6d.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("A separable portion of the object code, whose source code is excluded");
    _builder.newLine();
    _builder.append("from the Corresponding Source as a System Library, need not be");
    _builder.newLine();
    _builder.append("included in conveying the object code work.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("A \"User Product\" is either (1) a \"consumer product\", which means any");
    _builder.newLine();
    _builder.append("tangible personal property which is normally used for personal, family,");
    _builder.newLine();
    _builder.append("or household purposes, or (2) anything designed or sold for incorporation");
    _builder.newLine();
    _builder.append("into a dwelling.  In determining whether a product is a consumer product,");
    _builder.newLine();
    _builder.append("doubtful cases shall be resolved in favor of coverage.  For a particular");
    _builder.newLine();
    _builder.append("product received by a particular user, \"normally used\" refers to a");
    _builder.newLine();
    _builder.append("typical or common use of that class of product, regardless of the status");
    _builder.newLine();
    _builder.append("of the particular user or of the way in which the particular user");
    _builder.newLine();
    _builder.append("actually uses, or expects or is expected to use, the product.  A product");
    _builder.newLine();
    _builder.append("is a consumer product regardless of whether the product has substantial");
    _builder.newLine();
    _builder.append("commercial, industrial or non-consumer uses, unless such uses represent");
    _builder.newLine();
    _builder.append("the only significant mode of use of the product.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("\"Installation Information\" for a User Product means any methods,");
    _builder.newLine();
    _builder.append("procedures, authorization keys, or other information required to install");
    _builder.newLine();
    _builder.append("and execute modified versions of a covered work in that User Product from");
    _builder.newLine();
    _builder.append("a modified version of its Corresponding Source.  The information must");
    _builder.newLine();
    _builder.append("suffice to ensure that the continued functioning of the modified object");
    _builder.newLine();
    _builder.append("code is in no case prevented or interfered with solely because");
    _builder.newLine();
    _builder.append("modification has been made.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("If you convey an object code work under this section in, or with, or");
    _builder.newLine();
    _builder.append("specifically for use in, a User Product, and the conveying occurs as");
    _builder.newLine();
    _builder.append("part of a transaction in which the right of possession and use of the");
    _builder.newLine();
    _builder.append("User Product is transferred to the recipient in perpetuity or for a");
    _builder.newLine();
    _builder.append("fixed term (regardless of how the transaction is characterized), the");
    _builder.newLine();
    _builder.append("Corresponding Source conveyed under this section must be accompanied");
    _builder.newLine();
    _builder.append("by the Installation Information.  But this requirement does not apply");
    _builder.newLine();
    _builder.append("if neither you nor any third party retains the ability to install");
    _builder.newLine();
    _builder.append("modified object code on the User Product (for example, the work has");
    _builder.newLine();
    _builder.append("been installed in ROM).");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("The requirement to provide Installation Information does not include a");
    _builder.newLine();
    _builder.append("requirement to continue to provide support service, warranty, or updates");
    _builder.newLine();
    _builder.append("for a work that has been modified or installed by the recipient, or for");
    _builder.newLine();
    _builder.append("the User Product in which it has been modified or installed.  Access to a");
    _builder.newLine();
    _builder.append("network may be denied when the modification itself materially and");
    _builder.newLine();
    _builder.append("adversely affects the operation of the network or violates the rules and");
    _builder.newLine();
    _builder.append("protocols for communication across the network.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("Corresponding Source conveyed, and Installation Information provided,");
    _builder.newLine();
    _builder.append("in accord with this section must be in a format that is publicly");
    _builder.newLine();
    _builder.append("documented (and with an implementation available to the public in");
    _builder.newLine();
    _builder.append("source code form), and must require no special password or key for");
    _builder.newLine();
    _builder.append("unpacking, reading or copying.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("7. Additional Terms.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("\"Additional permissions\" are terms that supplement the terms of this");
    _builder.newLine();
    _builder.append("License by making exceptions from one or more of its conditions.");
    _builder.newLine();
    _builder.append("Additional permissions that are applicable to the entire Program shall");
    _builder.newLine();
    _builder.append("be treated as though they were included in this License, to the extent");
    _builder.newLine();
    _builder.append("that they are valid under applicable law.  If additional permissions");
    _builder.newLine();
    _builder.append("apply only to part of the Program, that part may be used separately");
    _builder.newLine();
    _builder.append("under those permissions, but the entire Program remains governed by");
    _builder.newLine();
    _builder.append("this License without regard to the additional permissions.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("When you convey a copy of a covered work, you may at your option");
    _builder.newLine();
    _builder.append("remove any additional permissions from that copy, or from any part of");
    _builder.newLine();
    _builder.append("it.  (Additional permissions may be written to require their own");
    _builder.newLine();
    _builder.append("removal in certain cases when you modify the work.)  You may place");
    _builder.newLine();
    _builder.append("additional permissions on material, added by you to a covered work,");
    _builder.newLine();
    _builder.append("for which you have or can give appropriate copyright permission.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("Notwithstanding any other provision of this License, for material you");
    _builder.newLine();
    _builder.append("add to a covered work, you may (if authorized by the copyright holders of");
    _builder.newLine();
    _builder.append("that material) supplement the terms of this License with terms:");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("a) Disclaiming warranty or limiting liability differently from the");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("terms of sections 15 and 16 of this License; or");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("b) Requiring preservation of specified reasonable legal notices or");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("author attributions in that material or in the Appropriate Legal");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("Notices displayed by works containing it; or");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("c) Prohibiting misrepresentation of the origin of that material, or");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("requiring that modified versions of such material be marked in");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("reasonable ways as different from the original version; or");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("d) Limiting the use for publicity purposes of names of licensors or");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("authors of the material; or");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("e) Declining to grant rights under trademark law for use of some");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("trade names, trademarks, or service marks; or");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("f) Requiring indemnification of licensors and authors of that");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("material by anyone who conveys the material (or modified versions of");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("it) with contractual assumptions of liability to the recipient, for");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("any liability that these contractual assumptions directly impose on");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("those licensors and authors.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("All other non-permissive additional terms are considered \"further");
    _builder.newLine();
    _builder.append("restrictions\" within the meaning of section 10.  If the Program as you");
    _builder.newLine();
    _builder.append("received it, or any part of it, contains a notice stating that it is");
    _builder.newLine();
    _builder.append("governed by this License along with a term that is a further");
    _builder.newLine();
    _builder.append("restriction, you may remove that term.  If a license document contains");
    _builder.newLine();
    _builder.append("a further restriction but permits relicensing or conveying under this");
    _builder.newLine();
    _builder.append("License, you may add to a covered work material governed by the terms");
    _builder.newLine();
    _builder.append("of that license document, provided that the further restriction does");
    _builder.newLine();
    _builder.append("not survive such relicensing or conveying.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("If you add terms to a covered work in accord with this section, you");
    _builder.newLine();
    _builder.append("must place, in the relevant source files, a statement of the");
    _builder.newLine();
    _builder.append("additional terms that apply to those files, or a notice indicating");
    _builder.newLine();
    _builder.append("where to find the applicable terms.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("Additional terms, permissive or non-permissive, may be stated in the");
    _builder.newLine();
    _builder.append("form of a separately written license, or stated as exceptions;");
    _builder.newLine();
    _builder.append("the above requirements apply either way.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("8. Termination.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("You may not propagate or modify a covered work except as expressly");
    _builder.newLine();
    _builder.append("provided under this License.  Any attempt otherwise to propagate or");
    _builder.newLine();
    _builder.append("modify it is void, and will automatically terminate your rights under");
    _builder.newLine();
    _builder.append("this License (including any patent licenses granted under the third");
    _builder.newLine();
    _builder.append("paragraph of section 11).");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("However, if you cease all violation of this License, then your");
    _builder.newLine();
    _builder.append("license from a particular copyright holder is reinstated (a)");
    _builder.newLine();
    _builder.append("provisionally, unless and until the copyright holder explicitly and");
    _builder.newLine();
    _builder.append("finally terminates your license, and (b) permanently, if the copyright");
    _builder.newLine();
    _builder.append("holder fails to notify you of the violation by some reasonable means");
    _builder.newLine();
    _builder.append("prior to 60 days after the cessation.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("Moreover, your license from a particular copyright holder is");
    _builder.newLine();
    _builder.append("reinstated permanently if the copyright holder notifies you of the");
    _builder.newLine();
    _builder.append("violation by some reasonable means, this is the first time you have");
    _builder.newLine();
    _builder.append("received notice of violation of this License (for any work) from that");
    _builder.newLine();
    _builder.append("copyright holder, and you cure the violation prior to 30 days after");
    _builder.newLine();
    _builder.append("your receipt of the notice.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("Termination of your rights under this section does not terminate the");
    _builder.newLine();
    _builder.append("licenses of parties who have received copies or rights from you under");
    _builder.newLine();
    _builder.append("this License.  If your rights have been terminated and not permanently");
    _builder.newLine();
    _builder.append("reinstated, you do not qualify to receive new licenses for the same");
    _builder.newLine();
    _builder.append("material under section 10.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("9. Acceptance Not Required for Having Copies.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("You are not required to accept this License in order to receive or");
    _builder.newLine();
    _builder.append("run a copy of the Program.  Ancillary propagation of a covered work");
    _builder.newLine();
    _builder.append("occurring solely as a consequence of using peer-to-peer transmission");
    _builder.newLine();
    _builder.append("to receive a copy likewise does not require acceptance.  However,");
    _builder.newLine();
    _builder.append("nothing other than this License grants you permission to propagate or");
    _builder.newLine();
    _builder.append("modify any covered work.  These actions infringe copyright if you do");
    _builder.newLine();
    _builder.append("not accept this License.  Therefore, by modifying or propagating a");
    _builder.newLine();
    _builder.append("covered work, you indicate your acceptance of this License to do so.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("10. Automatic Licensing of Downstream Recipients.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("Each time you convey a covered work, the recipient automatically");
    _builder.newLine();
    _builder.append("receives a license from the original licensors, to run, modify and");
    _builder.newLine();
    _builder.append("propagate that work, subject to this License.  You are not responsible");
    _builder.newLine();
    _builder.append("for enforcing compliance by third parties with this License.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("An \"entity transaction\" is a transaction transferring control of an");
    _builder.newLine();
    _builder.append("organization, or substantially all assets of one, or subdividing an");
    _builder.newLine();
    _builder.append("organization, or merging organizations.  If propagation of a covered");
    _builder.newLine();
    _builder.append("work results from an entity transaction, each party to that");
    _builder.newLine();
    _builder.append("transaction who receives a copy of the work also receives whatever");
    _builder.newLine();
    _builder.append("licenses to the work the party\'s predecessor in interest had or could");
    _builder.newLine();
    _builder.append("give under the previous paragraph, plus a right to possession of the");
    _builder.newLine();
    _builder.append("Corresponding Source of the work from the predecessor in interest, if");
    _builder.newLine();
    _builder.append("the predecessor has it or can get it with reasonable efforts.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("You may not impose any further restrictions on the exercise of the");
    _builder.newLine();
    _builder.append("rights granted or affirmed under this License.  For example, you may");
    _builder.newLine();
    _builder.append("not impose a license fee, royalty, or other charge for exercise of");
    _builder.newLine();
    _builder.append("rights granted under this License, and you may not initiate litigation");
    _builder.newLine();
    _builder.append("(including a cross-claim or counterclaim in a lawsuit) alleging that");
    _builder.newLine();
    _builder.append("any patent claim is infringed by making, using, selling, offering for");
    _builder.newLine();
    _builder.append("sale, or importing the Program or any portion of it.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("11. Patents.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("A \"contributor\" is a copyright holder who authorizes use under this");
    _builder.newLine();
    _builder.append("License of the Program or a work on which the Program is based.  The");
    _builder.newLine();
    _builder.append("work thus licensed is called the contributor\'s \"contributor version\".");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("A contributor\'s \"essential patent claims\" are all patent claims");
    _builder.newLine();
    _builder.append("owned or controlled by the contributor, whether already acquired or");
    _builder.newLine();
    _builder.append("hereafter acquired, that would be infringed by some manner, permitted");
    _builder.newLine();
    _builder.append("by this License, of making, using, or selling its contributor version,");
    _builder.newLine();
    _builder.append("but do not include claims that would be infringed only as a");
    _builder.newLine();
    _builder.append("consequence of further modification of the contributor version.  For");
    _builder.newLine();
    _builder.append("purposes of this definition, \"control\" includes the right to grant");
    _builder.newLine();
    _builder.append("patent sublicenses in a manner consistent with the requirements of");
    _builder.newLine();
    _builder.append("this License.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("Each contributor grants you a non-exclusive, worldwide, royalty-free");
    _builder.newLine();
    _builder.append("patent license under the contributor\'s essential patent claims, to");
    _builder.newLine();
    _builder.append("make, use, sell, offer for sale, import and otherwise run, modify and");
    _builder.newLine();
    _builder.append("propagate the contents of its contributor version.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("In the following three paragraphs, a \"patent license\" is any express");
    _builder.newLine();
    _builder.append("agreement or commitment, however denominated, not to enforce a patent");
    _builder.newLine();
    _builder.append("(such as an express permission to practice a patent or covenant not to");
    _builder.newLine();
    _builder.append("sue for patent infringement).  To \"grant\" such a patent license to a");
    _builder.newLine();
    _builder.append("party means to make such an agreement or commitment not to enforce a");
    _builder.newLine();
    _builder.append("patent against the party.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("If you convey a covered work, knowingly relying on a patent license,");
    _builder.newLine();
    _builder.append("and the Corresponding Source of the work is not available for anyone");
    _builder.newLine();
    _builder.append("to copy, free of charge and under the terms of this License, through a");
    _builder.newLine();
    _builder.append("publicly available network server or other readily accessible means,");
    _builder.newLine();
    _builder.append("then you must either (1) cause the Corresponding Source to be so");
    _builder.newLine();
    _builder.append("available, or (2) arrange to deprive yourself of the benefit of the");
    _builder.newLine();
    _builder.append("patent license for this particular work, or (3) arrange, in a manner");
    _builder.newLine();
    _builder.append("consistent with the requirements of this License, to extend the patent");
    _builder.newLine();
    _builder.append("license to downstream recipients.  \"Knowingly relying\" means you have");
    _builder.newLine();
    _builder.append("actual knowledge that, but for the patent license, your conveying the");
    _builder.newLine();
    _builder.append("covered work in a country, or your recipient\'s use of the covered work");
    _builder.newLine();
    _builder.append("in a country, would infringe one or more identifiable patents in that");
    _builder.newLine();
    _builder.append("country that you have reason to believe are valid.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("If, pursuant to or in connection with a single transaction or");
    _builder.newLine();
    _builder.append("arrangement, you convey, or propagate by procuring conveyance of, a");
    _builder.newLine();
    _builder.append("covered work, and grant a patent license to some of the parties");
    _builder.newLine();
    _builder.append("receiving the covered work authorizing them to use, propagate, modify");
    _builder.newLine();
    _builder.append("or convey a specific copy of the covered work, then the patent license");
    _builder.newLine();
    _builder.append("you grant is automatically extended to all recipients of the covered");
    _builder.newLine();
    _builder.append("work and works based on it.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("A patent license is \"discriminatory\" if it does not include within");
    _builder.newLine();
    _builder.append("the scope of its coverage, prohibits the exercise of, or is");
    _builder.newLine();
    _builder.append("conditioned on the non-exercise of one or more of the rights that are");
    _builder.newLine();
    _builder.append("specifically granted under this License.  You may not convey a covered");
    _builder.newLine();
    _builder.append("work if you are a party to an arrangement with a third party that is");
    _builder.newLine();
    _builder.append("in the business of distributing software, under which you make payment");
    _builder.newLine();
    _builder.append("to the third party based on the extent of your activity of conveying");
    _builder.newLine();
    _builder.append("the work, and under which the third party grants, to any of the");
    _builder.newLine();
    _builder.append("parties who would receive the covered work from you, a discriminatory");
    _builder.newLine();
    _builder.append("patent license (a) in connection with copies of the covered work");
    _builder.newLine();
    _builder.append("conveyed by you (or copies made from those copies), or (b) primarily");
    _builder.newLine();
    _builder.append("for and in connection with specific products or compilations that");
    _builder.newLine();
    _builder.append("contain the covered work, unless you entered into that arrangement,");
    _builder.newLine();
    _builder.append("or that patent license was granted, prior to 28 March 2007.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("Nothing in this License shall be construed as excluding or limiting");
    _builder.newLine();
    _builder.append("any implied license or other defenses to infringement that may");
    _builder.newLine();
    _builder.append("otherwise be available to you under applicable patent law.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("12. No Surrender of Others\' Freedom.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("If conditions are imposed on you (whether by court order, agreement or");
    _builder.newLine();
    _builder.append("otherwise) that contradict the conditions of this License, they do not");
    _builder.newLine();
    _builder.append("excuse you from the conditions of this License.  If you cannot convey a");
    _builder.newLine();
    _builder.append("covered work so as to satisfy simultaneously your obligations under this");
    _builder.newLine();
    _builder.append("License and any other pertinent obligations, then as a consequence you may");
    _builder.newLine();
    _builder.append("not convey it at all.  For example, if you agree to terms that obligate you");
    _builder.newLine();
    _builder.append("to collect a royalty for further conveying from those to whom you convey");
    _builder.newLine();
    _builder.append("the Program, the only way you could satisfy both those terms and this");
    _builder.newLine();
    _builder.append("License would be to refrain entirely from conveying the Program.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("13. Use with the GNU Affero General Public License.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("Notwithstanding any other provision of this License, you have");
    _builder.newLine();
    _builder.append("permission to link or combine any covered work with a work licensed");
    _builder.newLine();
    _builder.append("under version 3 of the GNU Affero General Public License into a single");
    _builder.newLine();
    _builder.append("combined work, and to convey the resulting work.  The terms of this");
    _builder.newLine();
    _builder.append("License will continue to apply to the part which is the covered work,");
    _builder.newLine();
    _builder.append("but the special requirements of the GNU Affero General Public License,");
    _builder.newLine();
    _builder.append("section 13, concerning interaction through a network will apply to the");
    _builder.newLine();
    _builder.append("combination as such.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("14. Revised Versions of this License.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("The Free Software Foundation may publish revised and/or new versions of");
    _builder.newLine();
    _builder.append("the GNU General Public License from time to time.  Such new versions will");
    _builder.newLine();
    _builder.append("be similar in spirit to the present version, but may differ in detail to");
    _builder.newLine();
    _builder.append("address new problems or concerns.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("Each version is given a distinguishing version number.  If the");
    _builder.newLine();
    _builder.append("Program specifies that a certain numbered version of the GNU General");
    _builder.newLine();
    _builder.append("Public License \"or any later version\" applies to it, you have the");
    _builder.newLine();
    _builder.append("option of following the terms and conditions either of that numbered");
    _builder.newLine();
    _builder.append("version or of any later version published by the Free Software");
    _builder.newLine();
    _builder.append("Foundation.  If the Program does not specify a version number of the");
    _builder.newLine();
    _builder.append("GNU General Public License, you may choose any version ever published");
    _builder.newLine();
    _builder.append("by the Free Software Foundation.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("If the Program specifies that a proxy can decide which future");
    _builder.newLine();
    _builder.append("versions of the GNU General Public License can be used, that proxy\'s");
    _builder.newLine();
    _builder.append("public statement of acceptance of a version permanently authorizes you");
    _builder.newLine();
    _builder.append("to choose that version for the Program.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("Later license versions may give you additional or different");
    _builder.newLine();
    _builder.append("permissions.  However, no additional obligations are imposed on any");
    _builder.newLine();
    _builder.append("author or copyright holder as a result of your choosing to follow a");
    _builder.newLine();
    _builder.append("later version.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("15. Disclaimer of Warranty.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("THERE IS NO WARRANTY FOR THE PROGRAM, TO THE EXTENT PERMITTED BY");
    _builder.newLine();
    _builder.append("APPLICABLE LAW.  EXCEPT WHEN OTHERWISE STATED IN WRITING THE COPYRIGHT");
    _builder.newLine();
    _builder.append("HOLDERS AND/OR OTHER PARTIES PROVIDE THE PROGRAM \"AS IS\" WITHOUT WARRANTY");
    _builder.newLine();
    _builder.append("OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO,");
    _builder.newLine();
    _builder.append("THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR");
    _builder.newLine();
    _builder.append("PURPOSE.  THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE PROGRAM");
    _builder.newLine();
    _builder.append("IS WITH YOU.  SHOULD THE PROGRAM PROVE DEFECTIVE, YOU ASSUME THE COST OF");
    _builder.newLine();
    _builder.append("ALL NECESSARY SERVICING, REPAIR OR CORRECTION.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("16. Limitation of Liability.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING");
    _builder.newLine();
    _builder.append("WILL ANY COPYRIGHT HOLDER, OR ANY OTHER PARTY WHO MODIFIES AND/OR CONVEYS");
    _builder.newLine();
    _builder.append("THE PROGRAM AS PERMITTED ABOVE, BE LIABLE TO YOU FOR DAMAGES, INCLUDING ANY");
    _builder.newLine();
    _builder.append("GENERAL, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES ARISING OUT OF THE");
    _builder.newLine();
    _builder.append("USE OR INABILITY TO USE THE PROGRAM (INCLUDING BUT NOT LIMITED TO LOSS OF");
    _builder.newLine();
    _builder.append("DATA OR DATA BEING RENDERED INACCURATE OR LOSSES SUSTAINED BY YOU OR THIRD");
    _builder.newLine();
    _builder.append("PARTIES OR A FAILURE OF THE PROGRAM TO OPERATE WITH ANY OTHER PROGRAMS),");
    _builder.newLine();
    _builder.append("EVEN IF SUCH HOLDER OR OTHER PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF");
    _builder.newLine();
    _builder.append("SUCH DAMAGES.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("17. Interpretation of Sections 15 and 16.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("If the disclaimer of warranty and limitation of liability provided");
    _builder.newLine();
    _builder.append("above cannot be given local legal effect according to their terms,");
    _builder.newLine();
    _builder.append("reviewing courts shall apply local law that most closely approximates");
    _builder.newLine();
    _builder.append("an absolute waiver of all civil liability in connection with the");
    _builder.newLine();
    _builder.append("Program, unless a warranty or assumption of liability accompanies a");
    _builder.newLine();
    _builder.append("copy of the Program in return for a fee.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("                     ");
    _builder.append("END OF TERMS AND CONDITIONS");
    _builder.newLine();
    _builder.newLine();
    _builder.append("            ");
    _builder.append("How to Apply These Terms to Your New Programs");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("If you develop a new program, and you want it to be of the greatest");
    _builder.newLine();
    _builder.append("possible use to the public, the best way to achieve this is to make it");
    _builder.newLine();
    _builder.append("free software which everyone can redistribute and change under these terms.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("To do so, attach the following notices to the program.  It is safest");
    _builder.newLine();
    _builder.append("to attach them to the start of each source file to most effectively");
    _builder.newLine();
    _builder.append("state the exclusion of warranty; and each file should have at least");
    _builder.newLine();
    _builder.append("the \"copyright\" line and a pointer to where the full notice is found.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<one line to give the program\'s name and a brief idea of what it does.>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("Copyright (C) <year>  <name of author>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("This program is free software: you can redistribute it and/or modify");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("it under the terms of the GNU General Public License as published by");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("the Free Software Foundation, either version 3 of the License, or");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("(at your option) any later version.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("This program is distributed in the hope that it will be useful,");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("but WITHOUT ANY WARRANTY; without even the implied warranty of");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("GNU General Public License for more details.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("You should have received a copy of the GNU General Public License");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("along with this program.  If not, see <http://www.gnu.org/licenses/>.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("Also add information on how to contact you by electronic and paper mail.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("If the program does terminal interaction, make it output a short");
    _builder.newLine();
    _builder.append("notice like this when it starts in an interactive mode:");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<program>  Copyright (C) <year>  <name of author>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("This program comes with ABSOLUTELY NO WARRANTY; for details type `show w\'.");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("This is free software, and you are welcome to redistribute it");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("under certain conditions; type `show c\' for details.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("The hypothetical commands `show w\' and `show c\' should show the appropriate");
    _builder.newLine();
    _builder.append("parts of the General Public License.  Of course, your program\'s commands");
    _builder.newLine();
    _builder.append("might be different; for a GUI interface, you would use an \"about box\".");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("You should also get your employer (if you work as a programmer) or school,");
    _builder.newLine();
    _builder.append("if any, to sign a \"copyright disclaimer\" for the program, if necessary.");
    _builder.newLine();
    _builder.append("For more information on this, and how to apply and follow the GNU GPL, see");
    _builder.newLine();
    _builder.append("<http://www.gnu.org/licenses/>.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("The GNU General Public License does not permit incorporating your program");
    _builder.newLine();
    _builder.append("into proprietary programs.  If your program is a subroutine library, you");
    _builder.newLine();
    _builder.append("may consider it more useful to permit linking proprietary applications with");
    _builder.newLine();
    _builder.append("the library.  If this is what you want to do, use the GNU Lesser General");
    _builder.newLine();
    _builder.append("Public License instead of this License.  But first, please read");
    _builder.newLine();
    _builder.append("<http://www.gnu.org/philosophy/why-not-lgpl.html>.");
    _builder.newLine();
    return _builder;
  }
}
