package org.zikula.modulestudio.generator.cartridges.zclassic.view.pagecomponents;

import de.guite.modulestudio.metamodel.Application;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.IFileSystemAccess;
import org.eclipse.xtext.xbase.lib.Extension;
import org.eclipse.xtext.xbase.lib.InputOutput;
import org.zikula.modulestudio.generator.extensions.GeneratorSettingsExtensions;
import org.zikula.modulestudio.generator.extensions.ModelBehaviourExtensions;
import org.zikula.modulestudio.generator.extensions.NamingExtensions;

@SuppressWarnings("all")
public class FilterSyntaxDialog {
  @Extension
  private GeneratorSettingsExtensions _generatorSettingsExtensions = new GeneratorSettingsExtensions();
  
  @Extension
  private ModelBehaviourExtensions _modelBehaviourExtensions = new ModelBehaviourExtensions();
  
  @Extension
  private NamingExtensions _namingExtensions = new NamingExtensions();
  
  public void generate(final Application it, final IFileSystemAccess fsa) {
    if (((!this._generatorSettingsExtensions.generateListBlock(it)) && (!this._generatorSettingsExtensions.generateListContentType(it)))) {
      return;
    }
    String fileName = "includeFilterSyntaxDialog.html.twig";
    String _viewPath = this._namingExtensions.getViewPath(it);
    String _plus = (_viewPath + fileName);
    boolean _shouldBeSkipped = this._namingExtensions.shouldBeSkipped(it, _plus);
    boolean _not = (!_shouldBeSkipped);
    if (_not) {
      InputOutput.<String>println("Generating filter syntax dialog");
      String _viewPath_1 = this._namingExtensions.getViewPath(it);
      String _plus_1 = (_viewPath_1 + fileName);
      boolean _shouldBeMarked = this._namingExtensions.shouldBeMarked(it, _plus_1);
      if (_shouldBeMarked) {
        fileName = "includeFilterSyntaxDialog.generated.html.twig";
      }
      String _viewPath_2 = this._namingExtensions.getViewPath(it);
      String _plus_2 = (_viewPath_2 + fileName);
      fsa.generateFile(_plus_2, this.dialogTemplate(it));
    }
  }
  
  private CharSequence dialogTemplate(final Application it) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("{# purpose of this template: show a modal dialog for explaining FilterUtil syntax #}");
    _builder.newLine();
    _builder.append("<div class=\"modal fade\" id=\"filterSyntaxModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"filterSyntaxModalLabel\" aria-hidden=\"true\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<div class=\"modal-dialog\">");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<div class=\"modal-content\">");
    _builder.newLine();
    _builder.append("            ");
    CharSequence _dialogHeader = this.dialogHeader(it);
    _builder.append(_dialogHeader, "            ");
    _builder.newLineIfNotEmpty();
    _builder.append("            ");
    CharSequence _dialogBody = this.dialogBody(it);
    _builder.append(_dialogBody, "            ");
    _builder.newLineIfNotEmpty();
    _builder.append("            ");
    CharSequence _dialogFooter = this.dialogFooter(it);
    _builder.append(_dialogFooter, "            ");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("</div>");
    _builder.newLine();
    return _builder;
  }
  
  private CharSequence dialogHeader(final Application it) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<div class=\"modal-header\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<button type=\"button\" class=\"close\" data-dismiss=\"modal\"><span aria-hidden=\"true\">&times;</span><span class=\"sr-only\">{{ __(\'Close\') }}</span></button>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<h4 class=\"modal-title\" id=\"filterSyntaxModalLabel\">{{ __(\'Filter syntax explained\') }}</h4>");
    _builder.newLine();
    _builder.append("</div>");
    _builder.newLine();
    return _builder;
  }
  
  private CharSequence dialogBody(final Application it) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<div class=\"modal-body\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<p>{{ __(\'It is possible to filter the list of retrieved items by specifying arbitrary filter expressions. This page shows how to create these expressions.\') }}</p>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<h4>{{ __(\'Example\') }}</h4>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<p>{{ __(\'The following filters assume that you have a list of persons whereby each person can have many addresses.\') }}</p>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<hr />");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<h4>{{ __(\'Table aliases\') }}</h4>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<p>{{ __(\'The main table, that is the entity being the primary subject of the query, is always known directly. That means, you can prepend \"tbl.\", but you do not need to.\') }}");
    _builder.newLine();
    _builder.append("       ");
    _builder.append("{{ __(\'All additional joined tables can be referenced by \"tblFoo\".\') }}");
    _builder.newLine();
    _builder.append("       ");
    _builder.append("{{ __(\'Thereby \"Foo\" does not mean the name of the joined entity, but the source or target alias of the corresponding relationship.\') }}");
    _builder.newLine();
    _builder.append("       ");
    _builder.append("{{ __(\'This has the advantage that it is possible to join a certain table multiple times. For example instead of having many addresses for a person one could also create two relationships for business and home addresses this way.\') }}");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<p>{{ __(\'So in our example we can reference Persons with \"tbl\" and addresses with \"tblAddresses\".\') }}</p>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<hr />");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<h4>{{ __(\'General syntax\') }}</h4>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<h5>{{ __(\'Filter statements\') }}</h5>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<p>{{ __(\'A filter consists of several statements.\') }} {{ __(\'Each statement is a set of field name, operator and value connected by a colon.\') }} {{ __(\'The operator defines the condition type (equal, lower than, etc.).\') }}</p>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<ul>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<li><code>firstName:eq:Peter</code> {{ __(\'The first name is Peter\') }}</li>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<li><code>tblAddresses.houseNumber:lt:100</code> {{ __(\'The house number of any address is lower than 100\') }}</li>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("</ul>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<h5>{{ __(\'Combining statements\') }}</h5>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<p>{{ __(\'Several statements can be connected by a comma , (AND) or an asterisk * (OR).\') }}</p>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<ul>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<li><code>firstName:eq:Peter,tblAddresses.houseNumber:lt:100</code> {{ __(\'The first name is Peter and the house number of any address is below 100.\') }}</li>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<li><code>firstName:eq:Peter*firstName:eq:Chris</code> {{ __(\'The first name equals either Peter or Chris\') }}</li>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("</ul>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<p>{{ __(\'Furthermore you can use brackets to group statements.\') }}</p>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<ul>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<li><code>(firstName:eq:Peter,tblAddresses.houseNumber:lt:100)*(firstName:eq:Chris,tblAddresses.houseNumber:lt:150)</code> {{ __(\'Either the first name is Peter and the house number of any address is below 100 or the first name is Chris and the house number of any address is below 150.\') }}</li>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("</ul>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<h4>{{ __(\'Operators\') }}</h4>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<ul>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<li><code>eq</code> {{ __(\'is equal.\') }}</li>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<li><code>ne</code> {{ __(\'is not equal.\') }}</li>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<li><code>lt</code> {{ __(\'is lower than.\') }}</li>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<li><code>le</code> {{ __(\'is lower or equal than.\') }}</li>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<li><code>gt</code> {{ __(\'is greater than.\') }}</li>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<li><code>ge</code> {{ __(\'is greater or equal than.\') }}</li>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<li><code>search</code> {{ __(\'is any middle coincidence.\') }} {{ __(\'The term \"bar\" will match \"foobarthis\", but not \"foobar\" nor \"barfoo\".\') }}</li>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<li><code>like</code> {{ __(\'is like.\') }} {{ __(\'The value is scanned case insensitive.\') }} {{ __(\'Also you can use \"\\%\" as placeholder.\') }} {{ __(\'\"\\%bar\" will match \"FOObar\", \"Blubbar\" and so on, but not \"BarFoo\".\') }}</li>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<li><code>likefirst</code> {\'is for coincidences at the beginning.\') }} {{ __(\'The term \"foo\" will match \"fOo\", \"FOObar\", \"FooBlub\" and so on, but not \"AnotherFoo\".\') }}</li>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<li><code>likelast</code> {\'is for coincidences at the end.\') }} {{ __(\'The term \"foo\" will match \"fOo\", \"AnotherFoo\" and so on, but not \"FoObar\" or \"FooBlub\".\') }}</li>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<li><code>null</code> {{ __(\'is Empty or NULL.\') }}</li>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<li><code>notnull</code> {{ __(\'is not empty and not NULL.\') }}</li>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("</ul>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<hr />");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<h4>{{ __(\'Special field types\') }}</h4>");
    _builder.newLine();
    {
      boolean _hasCategorisableEntities = this._modelBehaviourExtensions.hasCategorisableEntities(it);
      if (_hasCategorisableEntities) {
        _builder.append("    ");
        _builder.append("<h5>{{ __(\'Categories\') }}</h5>");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("<p>{{ __(\'If a \"Person\" has Categories support then you can also filter by category id or name.\') }}</p>");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("<ul>");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("    ");
        _builder.append("<li><code>categories:eq:4</code> {{ __(\'Person is assigned to category with id \"4\".\') }}</li>");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("    ");
        _builder.append("<li><code>categories:eq:Sports</code> {{ __(\'Person is assigned to category with name \"Sports\".\') }}</li>");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("    ");
        _builder.append("<li><code>categories:ne:4</code> {{ __(\'Person is not assigned to category with id \"4\".\') }}</li>");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("    ");
        _builder.append("<li><code>categories:sub:Sports</code> {{ __(\'Person is assigned to category with name \"Sports\" or one of it\\\'s sub categories.\') }}</li>");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("</ul>");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("<p>{{ __(\'The field name \"categories\" is the default name for category fields. However, in practice we need to define different field names for possibly several registries.\') }}</p>");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("<p>{{ __(\'Therefore we create a virtual fields for each registry property.\') }} {{ __(\'So instead of \"categories\" use \"categoriesFoo\" whereby \"Foo\" is the property name for the desired registry, for example \"Main\".\') }}</p>");
        _builder.newLine();
      }
    }
    _builder.append("    ");
    _builder.append("<h5>{{ __(\'Dates\') }}</h5>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<p>{{ __(\'When filtering for dates you can use convenient extensions and even time periods.\') }}</p>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<ul>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<li>{{ __(\'Prepend one of the keywords \"year\", \"month\", \"week\", \"day\", \"hour\", \"min\" followed by a colon to search for a time period.\') }}");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<ul>");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("<li><code>date:eq:year:15.07.2016</code> {{ __(\'All items with a date in year 2016.\') }}</li>");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("<li><code>date:eq:month:15.07.2016</code> {{ __(\'All items with a date in July 2016.\') }}</li>");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("</ul>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("</li>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<li>{{ __(\'You can use relative time information according to the GNU Date Input Formats syntax.\') }}");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<ul>");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("<li><code>date:eq:today</code> {{ __(\'All items with date of today.\') }}</li>");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("<li><code>date:ge:24 hours</code> {{ __(\'All items with date up from 24 hours ago.\') }}</li>");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("<li><code>date:eq:last year</code> {{ __(\'All items with date in the last year.\') }}</li>");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("</ul>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("</li>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("</ul>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<h6>{{ __(\'Date operators\') }}</h6>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<ul>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<li><code>eq</code> {{ __(\'is equal.\') }}</li>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<li><code>ne</code> {{ __(\'is not equal.\') }}</li>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<li><code>gt</code> {{ __(\'is greater than.\') }} {{ __(\'For time periods: End of the given period. \"Date:gt:today\" matches all items with date of tomorrow or later.\') }}</li>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<li><code>ge</code> {{ __(\'is greater or equal than.\') }} {{ __(\'For time periods: Begin of the given period. \"Date:ge:today\" matches all items with date of today or later.\') }}</li>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<li><code>lt</code> {{ __(\'is lower than.\') }} {{ __(\'For time periods: Begin of the given period. \"Date:lt:today\" matches all items with date of yesterday or before.\') }}</li>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<li><code>le</code> {{ __(\'is lower or equal than.\') }} {{ __(\'For time periods: End of the given period. \"Date:le:today\" matches all items with date of today or before.\') }}</li>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("</ul>");
    _builder.newLine();
    _builder.append("</div>");
    _builder.newLine();
    return _builder;
  }
  
  private CharSequence dialogFooter(final Application it) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<div class=\"modal-footer\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<button type=\"button\" class=\"btn btn-primary\" data-dismiss=\"modal\">{{ __(\'Close\') }}</button>");
    _builder.newLine();
    _builder.append("</div>");
    _builder.newLine();
    return _builder;
  }
}
