name: Feature Request
description: Tell us about a new addition you want to see
labels: [feature]
assignees: 'Guite'
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Pleaseprovide a brief overview of what the new feature is all about.
      render: bash
    validations:
      required: true
  - type: textarea
    id: desired-behavior
    attributes:
      label: Desired behaviour
      description: Please tell us, how the new feature should work, be specific.
      placeholder: Describe what you imagine!
      render: bash
    validations:
      required: true
  - type: textarea
    id: possible-solution
    attributes:
      label: Possible solution
      description: Not required, but suggest ideas on how to implement the addition or change.
      render: bash
  - type: textarea
    id: context
    attributes:
      label: Context
      description:  Why does this feature matter to you? What unique circumstances do you have? If this involves a rather complex scenario maybe attach your .mostapp model file.
      render: bash
  - type: dropdown
    id: most-version
    attributes:
      label: ModuleStudio version
      description: Which version of ModuleStudio are you running?
      options:
        - 2.0.0 (Default)
        - 1.4.0
        - latest git
    validations:
      required: true
  - type: dropdown
    id: oeprating-system
    attributes:
      label: Operating system
      description: Which operating system are you running?
      options:
        - Windows
        - Linux
        - MacOS
    validations:
      required: true
  - type: dropdown
    id: symfony-target-version
    attributes:
      label: Symfony target in model
      description: Which Symfony target version do you have configured in your model?
      options:
        - SF73
        - SF72
    validations:
      required: true
  - type: dropdown
    id: zikula-version
    attributes:
      label: Zikula version
      description: Which Zikula version are you running?
      options:
        - 4.x-git
        - 3.1.x
        - 3.0.x
    validations:
      required: true
  - type: dropdown
    id: php-version
    attributes:
      label: PHP version
      description: Which PHP version are you running?
      options:
        - 8.4.x
        - 8.3.x
        - 8.2.x
    validations:
      required: true
