/*
 * generated by Xtext see
 * de.guite.modulestudio.mostdsl.tests/src-gen/MostDslInjectorProvider.java
 */
package org.zikula.modulestudio.generator.tests.lib;

import org.eclipse.xtext.junit4.GlobalRegistries;
import org.eclipse.xtext.junit4.GlobalRegistries.GlobalStateMemento;
import org.eclipse.xtext.junit4.IInjectorProvider;
import org.eclipse.xtext.junit4.IRegistryConfigurator;

import com.google.inject.Injector;

import de.guite.modulestudio.MostDslStandaloneSetup;

public class MostDslInjectorProvider implements IInjectorProvider,
        IRegistryConfigurator {

    protected GlobalStateMemento stateBeforeInjectorCreation;
    protected GlobalStateMemento stateAfterInjectorCreation;
    protected Injector injector;

    static {
        GlobalRegistries.initializeDefaults();
    }

    @Override
    public Injector getInjector() {
        if (injector == null) {
            stateBeforeInjectorCreation = GlobalRegistries
                    .makeCopyOfGlobalState();
            this.injector = internalCreateInjector();
            stateAfterInjectorCreation = GlobalRegistries
                    .makeCopyOfGlobalState();
        }
        return injector;
    }

    protected static Injector internalCreateInjector() {
        return new MostDslStandaloneSetup()
                .createInjectorAndDoEMFRegistration();
    }

    @Override
    public void restoreRegistry() {
        stateBeforeInjectorCreation.restoreGlobalState();
    }

    @Override
    public void setupRegistry() {
        getInjector();
        stateAfterInjectorCreation.restoreGlobalState();
    }
}
