package org.zikula.modulestudio.generator.cartridges.zclassic.smallstuff.documents;

import de.guite.modulestudio.metamodel.modulestudio.Application;
import org.eclipse.xtend2.lib.StringConcatenation;

@SuppressWarnings("all")
public class License_LGPL {
  public CharSequence generate(final Application it) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("                   ");
    _builder.append("GNU LESSER GENERAL PUBLIC LICENSE");
    _builder.newLine();
    _builder.append("                       ");
    _builder.append("Version 3, 29 June 2007");
    _builder.newLine();
    _builder.newLine();
    _builder.append(" ");
    _builder.append("Copyright (C) 2007 Free Software Foundation, Inc. <http://fsf.org/>");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("Everyone is permitted to copy and distribute verbatim copies");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("of this license document, but changing it is not allowed.");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("This version of the GNU Lesser General Public License incorporates");
    _builder.newLine();
    _builder.append("the terms and conditions of version 3 of the GNU General Public");
    _builder.newLine();
    _builder.append("License, supplemented by the additional permissions listed below.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("0. Additional Definitions.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("As used herein, \"this License\" refers to version 3 of the GNU Lesser");
    _builder.newLine();
    _builder.append("General Public License, and the \"GNU GPL\" refers to version 3 of the GNU");
    _builder.newLine();
    _builder.append("General Public License.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("\"The Library\" refers to a covered work governed by this License,");
    _builder.newLine();
    _builder.append("other than an Application or a Combined Work as defined below.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("An \"Application\" is any work that makes use of an interface provided");
    _builder.newLine();
    _builder.append("by the Library, but which is not otherwise based on the Library.");
    _builder.newLine();
    _builder.append("Defining a subclass of a class defined by the Library is deemed a mode");
    _builder.newLine();
    _builder.append("of using an interface provided by the Library.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("A \"Combined Work\" is a work produced by combining or linking an");
    _builder.newLine();
    _builder.append("Application with the Library.  The particular version of the Library");
    _builder.newLine();
    _builder.append("with which the Combined Work was made is also called the \"Linked");
    _builder.newLine();
    _builder.append("Version\".");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("The \"Minimal Corresponding Source\" for a Combined Work means the");
    _builder.newLine();
    _builder.append("Corresponding Source for the Combined Work, excluding any source code");
    _builder.newLine();
    _builder.append("for portions of the Combined Work that, considered in isolation, are");
    _builder.newLine();
    _builder.append("based on the Application, and not on the Linked Version.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("The \"Corresponding Application Code\" for a Combined Work means the");
    _builder.newLine();
    _builder.append("object code and/or source code for the Application, including any data");
    _builder.newLine();
    _builder.append("and utility programs needed for reproducing the Combined Work from the");
    _builder.newLine();
    _builder.append("Application, but excluding the System Libraries of the Combined Work.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("1. Exception to Section 3 of the GNU GPL.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("You may convey a covered work under sections 3 and 4 of this License");
    _builder.newLine();
    _builder.append("without being bound by section 3 of the GNU GPL.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("2. Conveying Modified Versions.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("If you modify a copy of the Library, and, in your modifications, a");
    _builder.newLine();
    _builder.append("facility refers to a function or data to be supplied by an Application");
    _builder.newLine();
    _builder.append("that uses the facility (other than as an argument passed when the");
    _builder.newLine();
    _builder.append("facility is invoked), then you may convey a copy of the modified");
    _builder.newLine();
    _builder.append("version:");
    _builder.newLine();
    _builder.newLine();
    _builder.append("   ");
    _builder.append("a) under this License, provided that you make a good faith effort to");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("ensure that, in the event an Application does not supply the");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("function or data, the facility still operates, and performs");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("whatever part of its purpose remains meaningful, or");
    _builder.newLine();
    _builder.newLine();
    _builder.append("   ");
    _builder.append("b) under the GNU GPL, with none of the additional permissions of");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("this License applicable to that copy.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("3. Object Code Incorporating Material from Library Header Files.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("The object code form of an Application may incorporate material from");
    _builder.newLine();
    _builder.append("a header file that is part of the Library.  You may convey such object");
    _builder.newLine();
    _builder.append("code under terms of your choice, provided that, if the incorporated");
    _builder.newLine();
    _builder.append("material is not limited to numerical parameters, data structure");
    _builder.newLine();
    _builder.append("layouts and accessors, or small macros, inline functions and templates");
    _builder.newLine();
    _builder.append("(ten or fewer lines in length), you do both of the following:");
    _builder.newLine();
    _builder.newLine();
    _builder.append("   ");
    _builder.append("a) Give prominent notice with each copy of the object code that the");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("Library is used in it and that the Library and its use are");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("covered by this License.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("   ");
    _builder.append("b) Accompany the object code with a copy of the GNU GPL and this license");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("document.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("4. Combined Works.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("You may convey a Combined Work under terms of your choice that,");
    _builder.newLine();
    _builder.append("taken together, effectively do not restrict modification of the");
    _builder.newLine();
    _builder.append("portions of the Library contained in the Combined Work and reverse");
    _builder.newLine();
    _builder.append("engineering for debugging such modifications, if you also do each of");
    _builder.newLine();
    _builder.append("the following:");
    _builder.newLine();
    _builder.newLine();
    _builder.append("   ");
    _builder.append("a) Give prominent notice with each copy of the Combined Work that");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("the Library is used in it and that the Library and its use are");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("covered by this License.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("   ");
    _builder.append("b) Accompany the Combined Work with a copy of the GNU GPL and this license");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("document.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("   ");
    _builder.append("c) For a Combined Work that displays copyright notices during");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("execution, include the copyright notice for the Library among");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("these notices, as well as a reference directing the user to the");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("copies of the GNU GPL and this license document.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("   ");
    _builder.append("d) Do one of the following:");
    _builder.newLine();
    _builder.newLine();
    _builder.append("       ");
    _builder.append("0) Convey the Minimal Corresponding Source under the terms of this");
    _builder.newLine();
    _builder.append("       ");
    _builder.append("License, and the Corresponding Application Code in a form");
    _builder.newLine();
    _builder.append("       ");
    _builder.append("suitable for, and under terms that permit, the user to");
    _builder.newLine();
    _builder.append("       ");
    _builder.append("recombine or relink the Application with a modified version of");
    _builder.newLine();
    _builder.append("       ");
    _builder.append("the Linked Version to produce a modified Combined Work, in the");
    _builder.newLine();
    _builder.append("       ");
    _builder.append("manner specified by section 6 of the GNU GPL for conveying");
    _builder.newLine();
    _builder.append("       ");
    _builder.append("Corresponding Source.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("       ");
    _builder.append("1) Use a suitable shared library mechanism for linking with the");
    _builder.newLine();
    _builder.append("       ");
    _builder.append("Library.  A suitable mechanism is one that (a) uses at run time");
    _builder.newLine();
    _builder.append("       ");
    _builder.append("a copy of the Library already present on the user\'s computer");
    _builder.newLine();
    _builder.append("       ");
    _builder.append("system, and (b) will operate properly with a modified version");
    _builder.newLine();
    _builder.append("       ");
    _builder.append("of the Library that is interface-compatible with the Linked");
    _builder.newLine();
    _builder.append("       ");
    _builder.append("Version.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("   ");
    _builder.append("e) Provide Installation Information, but only if you would otherwise");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("be required to provide such information under section 6 of the");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("GNU GPL, and only to the extent that such information is");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("necessary to install and execute a modified version of the");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("Combined Work produced by recombining or relinking the");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("Application with a modified version of the Linked Version. (If");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("you use option 4d0, the Installation Information must accompany");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("the Minimal Corresponding Source and Corresponding Application");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("Code. If you use option 4d1, you must provide the Installation");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("Information in the manner specified by section 6 of the GNU GPL");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("for conveying Corresponding Source.)");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("5. Combined Libraries.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("You may place library facilities that are a work based on the");
    _builder.newLine();
    _builder.append("Library side by side in a single library together with other library");
    _builder.newLine();
    _builder.append("facilities that are not Applications and are not covered by this");
    _builder.newLine();
    _builder.append("License, and convey such a combined library under terms of your");
    _builder.newLine();
    _builder.append("choice, if you do both of the following:");
    _builder.newLine();
    _builder.newLine();
    _builder.append("   ");
    _builder.append("a) Accompany the combined library with a copy of the same work based");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("on the Library, uncombined with any other library facilities,");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("conveyed under the terms of this License.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("   ");
    _builder.append("b) Give prominent notice with the combined library that part of it");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("is a work based on the Library, and explaining where to find the");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("accompanying uncombined form of the same work.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("6. Revised Versions of the GNU Lesser General Public License.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("The Free Software Foundation may publish revised and/or new versions");
    _builder.newLine();
    _builder.append("of the GNU Lesser General Public License from time to time. Such new");
    _builder.newLine();
    _builder.append("versions will be similar in spirit to the present version, but may");
    _builder.newLine();
    _builder.append("differ in detail to address new problems or concerns.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("Each version is given a distinguishing version number. If the");
    _builder.newLine();
    _builder.append("Library as you received it specifies that a certain numbered version");
    _builder.newLine();
    _builder.append("of the GNU Lesser General Public License \"or any later version\"");
    _builder.newLine();
    _builder.append("applies to it, you have the option of following the terms and");
    _builder.newLine();
    _builder.append("conditions either of that published version or of any later version");
    _builder.newLine();
    _builder.append("published by the Free Software Foundation. If the Library as you");
    _builder.newLine();
    _builder.append("received it does not specify a version number of the GNU Lesser");
    _builder.newLine();
    _builder.append("General Public License, you may choose any version of the GNU Lesser");
    _builder.newLine();
    _builder.append("General Public License ever published by the Free Software Foundation.");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("If the Library as you received it specifies that a proxy can decide");
    _builder.newLine();
    _builder.append("whether future versions of the GNU Lesser General Public License shall");
    _builder.newLine();
    _builder.append("apply, that proxy\'s public statement of acceptance of any version is");
    _builder.newLine();
    _builder.append("permanent authorization for you to choose that version for the");
    _builder.newLine();
    _builder.append("Library.");
    _builder.newLine();
    return _builder;
  }
}
