package org.zikula.modulestudio.generator.cartridges.zclassic.smallstuff;

import com.google.common.base.Objects;
import com.google.inject.Inject;
import de.guite.modulestudio.metamodel.modulestudio.Application;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.IFileSystemAccess;
import org.eclipse.xtext.xbase.lib.Extension;
import org.eclipse.xtext.xbase.lib.Functions.Function0;
import org.zikula.modulestudio.generator.extensions.FormattingExtensions;
import org.zikula.modulestudio.generator.extensions.NamingExtensions;
import org.zikula.modulestudio.generator.extensions.Utils;

@SuppressWarnings("all")
public class ComposerFile {
  @Inject
  @Extension
  private FormattingExtensions _formattingExtensions = new Function0<FormattingExtensions>() {
    public FormattingExtensions apply() {
      FormattingExtensions _formattingExtensions = new FormattingExtensions();
      return _formattingExtensions;
    }
  }.apply();
  
  @Inject
  @Extension
  private NamingExtensions _namingExtensions = new Function0<NamingExtensions>() {
    public NamingExtensions apply() {
      NamingExtensions _namingExtensions = new NamingExtensions();
      return _namingExtensions;
    }
  }.apply();
  
  @Inject
  @Extension
  private Utils _utils = new Function0<Utils>() {
    public Utils apply() {
      Utils _utils = new Utils();
      return _utils;
    }
  }.apply();
  
  public void generate(final Application it, final IFileSystemAccess fsa) {
    boolean _targets = this._utils.targets(it, "1.3.5");
    if (_targets) {
      return;
    }
    String _appSourcePath = this._namingExtensions.getAppSourcePath(it);
    String _plus = (_appSourcePath + "composer.json");
    CharSequence _composerFile = this.composerFile(it);
    fsa.generateFile(_plus, _composerFile);
  }
  
  private CharSequence composerFile(final Application it) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("{");
    _builder.newLine();
    _builder.append("    ");
    CharSequence _composerContent = this.composerContent(it);
    _builder.append(_composerContent, "    ");
    _builder.newLineIfNotEmpty();
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }
  
  private CharSequence composerContent(final Application it) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("\"name\": \"");
    String _vendor = it.getVendor();
    String _formatForDB = this._formattingExtensions.formatForDB(_vendor);
    _builder.append(_formatForDB, "");
    _builder.append("/");
    String _name = it.getName();
    String _formatForDB_1 = this._formattingExtensions.formatForDB(_name);
    _builder.append(_formatForDB_1, "");
    _builder.append("\",");
    _builder.newLineIfNotEmpty();
    _builder.append("\"description\": \"");
    {
      boolean _and = false;
      String _documentation = it.getDocumentation();
      boolean _tripleNotEquals = (_documentation != null);
      if (!_tripleNotEquals) {
        _and = false;
      } else {
        String _documentation_1 = it.getDocumentation();
        boolean _notEquals = (!Objects.equal(_documentation_1, ""));
        _and = (_tripleNotEquals && _notEquals);
      }
      if (_and) {
        String _documentation_2 = it.getDocumentation();
        String _replaceAll = _documentation_2.replaceAll("\'", "\\\'");
        _builder.append(_replaceAll, "");
      } else {
        String _appName = this._utils.appName(it);
        _builder.append(_appName, "");
        _builder.append(" module generated by ModuleStudio ");
        String _msVersion = this._utils.msVersion();
        _builder.append(_msVersion, "");
        _builder.append(".");
      }
    }
    _builder.append("\",");
    _builder.newLineIfNotEmpty();
    _builder.append("\"version\": \"");
    String _version = it.getVersion();
    _builder.append(_version, "");
    _builder.append("\",");
    _builder.newLineIfNotEmpty();
    _builder.append("\"type\": \"zikula-module\",");
    _builder.newLine();
    _builder.append("\"license\": \"");
    String _licenseSPDX = this.licenseSPDX(it);
    _builder.append(_licenseSPDX, "");
    _builder.append("\",");
    _builder.newLineIfNotEmpty();
    _builder.append("\"authors\": [");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("{");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("\"name\": \"");
    String _author = it.getAuthor();
    _builder.append(_author, "        ");
    _builder.append("\",");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    _builder.append("\"email\": \"");
    String _email = it.getEmail();
    _builder.append(_email, "        ");
    _builder.append("\",");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    _builder.append("\"homepage\": \"");
    String _url = it.getUrl();
    _builder.append(_url, "        ");
    _builder.append("\"");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("],");
    _builder.newLine();
    _builder.append("\"autoload\": {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("\"psr-0\": { \"");
    String _vendor_1 = it.getVendor();
    String _formatForCodeCapital = this._formattingExtensions.formatForCodeCapital(_vendor_1);
    _builder.append(_formatForCodeCapital, "    ");
    _builder.append("\\\\");
    String _name_1 = it.getName();
    String _formatForCodeCapital_1 = this._formattingExtensions.formatForCodeCapital(_name_1);
    _builder.append(_formatForCodeCapital_1, "    ");
    _builder.append("Module\\\\\": \"\" }");
    _builder.newLineIfNotEmpty();
    _builder.append("},");
    _builder.newLine();
    _builder.append("\"require\": {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("\"php\": \">5.3.3\"");
    _builder.newLine();
    _builder.append("},");
    _builder.newLine();
    _builder.append("\"suggest\": {");
    _builder.newLine();
    _builder.append("},");
    _builder.newLine();
    _builder.append("\"extra\": {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("\"zikula\": {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("\"class\": \"");
    String _vendor_2 = it.getVendor();
    String _formatForCodeCapital_2 = this._formattingExtensions.formatForCodeCapital(_vendor_2);
    _builder.append(_formatForCodeCapital_2, "        ");
    _builder.append("\\\\");
    String _name_2 = it.getName();
    String _formatForCodeCapital_3 = this._formattingExtensions.formatForCodeCapital(_name_2);
    _builder.append(_formatForCodeCapital_3, "        ");
    _builder.append("Module\\\\");
    String _appName_1 = this._utils.appName(it);
    _builder.append(_appName_1, "        ");
    _builder.append("\"");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }
  
  private String licenseSPDX(final Application it) {
    String _switchResult = null;
    String _license = it.getLicense();
    final String getLicense = _license;
    boolean _matched = false;
    if (!_matched) {
      if (Objects.equal(getLicense,"Academic Free License v1.1")) {
        _matched=true;
        _switchResult = "AFL-1.1";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"AFL-1.1")) {
        _matched=true;
        _switchResult = "AFL-1.1";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Academic Free License v1.2")) {
        _matched=true;
        _switchResult = "AFL-1.2";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"AFL-1.2")) {
        _matched=true;
        _switchResult = "AFL-1.2";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Academic Free License v2.0")) {
        _matched=true;
        _switchResult = "AFL-2.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"AFL-2.0")) {
        _matched=true;
        _switchResult = "AFL-2.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Academic Free License v2.1")) {
        _matched=true;
        _switchResult = "AFL-2.1";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"AFL-2.1")) {
        _matched=true;
        _switchResult = "AFL-2.1";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Academic Free License v3.0")) {
        _matched=true;
        _switchResult = "AFL-3.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"AFL-3.0")) {
        _matched=true;
        _switchResult = "AFL-3.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Adaptive Public License 1.0")) {
        _matched=true;
        _switchResult = "APL-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"APL-1.0")) {
        _matched=true;
        _switchResult = "APL-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"ANTLR Software Rights Notice")) {
        _matched=true;
        _switchResult = "ANTLR-PD";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"ANTLR-PD")) {
        _matched=true;
        _switchResult = "ANTLR-PD";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Apache License 1.0")) {
        _matched=true;
        _switchResult = "Apache-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Apache-1.0")) {
        _matched=true;
        _switchResult = "Apache-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Apache License 1.1")) {
        _matched=true;
        _switchResult = "Apache-1.1";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Apache-1.1")) {
        _matched=true;
        _switchResult = "Apache-1.1";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Apache License 2.0")) {
        _matched=true;
        _switchResult = "Apache-2.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Apache-2.0")) {
        _matched=true;
        _switchResult = "Apache-2.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Apple Public Source License 1.0")) {
        _matched=true;
        _switchResult = "APSL-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"APSL-1.0")) {
        _matched=true;
        _switchResult = "APSL-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Apple Public Source License 1.1")) {
        _matched=true;
        _switchResult = "APSL-1.1";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"APSL-1.1")) {
        _matched=true;
        _switchResult = "APSL-1.1";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Apple Public Source License 1.2")) {
        _matched=true;
        _switchResult = "APSL-1.2";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"APSL-1.2")) {
        _matched=true;
        _switchResult = "APSL-1.2";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Apple Public Source License 2.0")) {
        _matched=true;
        _switchResult = "APSL-2.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"APSL-2.0")) {
        _matched=true;
        _switchResult = "APSL-2.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Artistic License 1.0")) {
        _matched=true;
        _switchResult = "Artistic-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Artistic-1.0")) {
        _matched=true;
        _switchResult = "Artistic-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Artistic License 2.0")) {
        _matched=true;
        _switchResult = "Artistic-2.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Artistic-2.0")) {
        _matched=true;
        _switchResult = "Artistic-2.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Attribution Assurance License")) {
        _matched=true;
        _switchResult = "AAL";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"AAL")) {
        _matched=true;
        _switchResult = "AAL";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Boost Software License 1.0")) {
        _matched=true;
        _switchResult = "BSL-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"BSL-1.0")) {
        _matched=true;
        _switchResult = "BSL-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"BSD 2-clause \"Simplified\" License")) {
        _matched=true;
        _switchResult = "BSD-2-Clause";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"BSD-2-Clause")) {
        _matched=true;
        _switchResult = "BSD-2-Clause";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"BSD 2-clause \"NetBSD\" License")) {
        _matched=true;
        _switchResult = "BSD-2-Clause-NetBSD";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"BSD-2-Clause-NetBSD")) {
        _matched=true;
        _switchResult = "BSD-2-Clause-NetBSD";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"BSD 2-clause \"FreeBSD\" License")) {
        _matched=true;
        _switchResult = "BSD-2-Clause-FreeBSD";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"BSD-2-Clause-FreeBSD")) {
        _matched=true;
        _switchResult = "BSD-2-Clause-FreeBSD";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"BSD 3-clause \"New\" or \"Revised\" License")) {
        _matched=true;
        _switchResult = "BSD-3-Clause";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"BSD-3-Clause")) {
        _matched=true;
        _switchResult = "BSD-3-Clause";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"BSD 4-clause \"Original\" or \"Old\" License")) {
        _matched=true;
        _switchResult = "BSD-4-Clause";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"BSD-4-Clause")) {
        _matched=true;
        _switchResult = "BSD-4-Clause";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"BSD-4-Clause (University of California-Specific)")) {
        _matched=true;
        _switchResult = "BSD-4-Clause-UC";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"BSD-4-Clause-UC")) {
        _matched=true;
        _switchResult = "BSD-4-Clause-UC";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"CeCILL Free Software License Agreement v1.0")) {
        _matched=true;
        _switchResult = "CECILL-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"CECILL-1.0")) {
        _matched=true;
        _switchResult = "CECILL-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"CeCILL Free Software License Agreement v1.1")) {
        _matched=true;
        _switchResult = "CECILL-1.1";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"CECILL-1.1")) {
        _matched=true;
        _switchResult = "CECILL-1.1";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"CeCILL Free Software License Agreement v2.0")) {
        _matched=true;
        _switchResult = "CECILL-2.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"CECILL-2.0")) {
        _matched=true;
        _switchResult = "CECILL-2.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"CeCILL-B Free Software License Agreement")) {
        _matched=true;
        _switchResult = "CECILL-B";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"CECILL-B")) {
        _matched=true;
        _switchResult = "CECILL-B";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"CeCILL-C Free Software License Agreement")) {
        _matched=true;
        _switchResult = "CECILL-C";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"CECILL-C")) {
        _matched=true;
        _switchResult = "CECILL-C";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Clarified Artistic License")) {
        _matched=true;
        _switchResult = "ClArtistic";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"ClArtistic")) {
        _matched=true;
        _switchResult = "ClArtistic";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"CNRI Python Open Source GPL Compatible License Agreement")) {
        _matched=true;
        _switchResult = "CNRI-Python-GPL-Compatible";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"CNRI-Python-GPL-Compatible")) {
        _matched=true;
        _switchResult = "CNRI-Python-GPL-Compatible";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"CNRI Python License")) {
        _matched=true;
        _switchResult = "CNRI-Python";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"CNRI-Python")) {
        _matched=true;
        _switchResult = "CNRI-Python";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Common Development and Distribution License 1.0")) {
        _matched=true;
        _switchResult = "CDDL-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"CDDL-1.0")) {
        _matched=true;
        _switchResult = "CDDL-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Common Development and Distribution License 1.1")) {
        _matched=true;
        _switchResult = "CDDL-1.1";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"CDDL-1.1")) {
        _matched=true;
        _switchResult = "CDDL-1.1";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Common Public Attribution License 1.0")) {
        _matched=true;
        _switchResult = "CPAL-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"CPAL-1.0")) {
        _matched=true;
        _switchResult = "CPAL-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Common Public License 1.0")) {
        _matched=true;
        _switchResult = "CPL-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"CPL-1.0")) {
        _matched=true;
        _switchResult = "CPL-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Computer Associates Trusted Open Source License 1.1")) {
        _matched=true;
        _switchResult = "CATOSL-1.1";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"CATOSL-1.1")) {
        _matched=true;
        _switchResult = "CATOSL-1.1";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Creative Commons Attribution 1.0")) {
        _matched=true;
        _switchResult = "CC-BY-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"CC-BY-1.0")) {
        _matched=true;
        _switchResult = "CC-BY-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Creative Commons Attribution 2.0")) {
        _matched=true;
        _switchResult = "CC-BY-2.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"CC-BY-2.0")) {
        _matched=true;
        _switchResult = "CC-BY-2.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Creative Commons Attribution 2.5")) {
        _matched=true;
        _switchResult = "CC-BY-2.5";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"CC-BY-2.5")) {
        _matched=true;
        _switchResult = "CC-BY-2.5";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Creative Commons Attribution 3.0")) {
        _matched=true;
        _switchResult = "CC-BY-3.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"CC-BY-3.0")) {
        _matched=true;
        _switchResult = "CC-BY-3.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Creative Commons Attribution No Derivatives 1.0")) {
        _matched=true;
        _switchResult = "CC-BY-ND-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"CC-BY-ND-1.0")) {
        _matched=true;
        _switchResult = "CC-BY-ND-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Creative Commons Attribution No Derivatives 2.0")) {
        _matched=true;
        _switchResult = "CC-BY-ND-2.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"CC-BY-ND-2.0")) {
        _matched=true;
        _switchResult = "CC-BY-ND-2.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Creative Commons Attribution No Derivatives 2.5")) {
        _matched=true;
        _switchResult = "CC-BY-ND-2.5";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"CC-BY-ND-2.5")) {
        _matched=true;
        _switchResult = "CC-BY-ND-2.5";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Creative Commons Attribution No Derivatives 3.0")) {
        _matched=true;
        _switchResult = "CC-BY-ND-3.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"CC-BY-ND-3.0")) {
        _matched=true;
        _switchResult = "CC-BY-ND-3.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Creative Commons Attribution Non Commercial 1.0")) {
        _matched=true;
        _switchResult = "CC-BY-NC-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"CC-BY-NC-1.0")) {
        _matched=true;
        _switchResult = "CC-BY-NC-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Creative Commons Attribution Non Commercial 2.0")) {
        _matched=true;
        _switchResult = "CC-BY-NC-2.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"CC-BY-NC-2.0")) {
        _matched=true;
        _switchResult = "CC-BY-NC-2.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Creative Commons Attribution Non Commercial 2.5")) {
        _matched=true;
        _switchResult = "CC-BY-NC-2.5";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"CC-BY-NC-2.5")) {
        _matched=true;
        _switchResult = "CC-BY-NC-2.5";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Creative Commons Attribution Non Commercial 3.0")) {
        _matched=true;
        _switchResult = "CC-BY-NC-3.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"CC-BY-NC-3.0")) {
        _matched=true;
        _switchResult = "CC-BY-NC-3.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Creative Commons Attribution Non Commercial No Derivatives 1.0")) {
        _matched=true;
        _switchResult = "CC-BY-NC-ND-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"CC-BY-NC-ND-1.0")) {
        _matched=true;
        _switchResult = "CC-BY-NC-ND-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Creative Commons Attribution Non Commercial No Derivatives 2.0")) {
        _matched=true;
        _switchResult = "CC-BY-NC-ND-2.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"CC-BY-NC-ND-2.0")) {
        _matched=true;
        _switchResult = "CC-BY-NC-ND-2.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Creative Commons Attribution Non Commercial No Derivatives 2.5")) {
        _matched=true;
        _switchResult = "CC-BY-NC-ND-2.5";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"CC-BY-NC-ND-2.5")) {
        _matched=true;
        _switchResult = "CC-BY-NC-ND-2.5";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Creative Commons Attribution Non Commercial No Derivatives 3.0")) {
        _matched=true;
        _switchResult = "CC-BY-NC-ND-3.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"CC-BY-NC-ND-3.0")) {
        _matched=true;
        _switchResult = "CC-BY-NC-ND-3.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Creative Commons Attribution Non Commercial Share Alike 1.0")) {
        _matched=true;
        _switchResult = "CC-BY-NC-SA-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"CC-BY-NC-SA-1.0")) {
        _matched=true;
        _switchResult = "CC-BY-NC-SA-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Creative Commons Attribution Non Commercial Share Alike 2.0")) {
        _matched=true;
        _switchResult = "CC-BY-NC-SA-2.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"CC-BY-NC-SA-2.0")) {
        _matched=true;
        _switchResult = "CC-BY-NC-SA-2.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Creative Commons Attribution Non Commercial Share Alike 2.5")) {
        _matched=true;
        _switchResult = "CC-BY-NC-SA-2.5";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"CC-BY-NC-SA-2.5")) {
        _matched=true;
        _switchResult = "CC-BY-NC-SA-2.5";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Creative Commons Attribution Non Commercial Share Alike 3.0")) {
        _matched=true;
        _switchResult = "CC-BY-NC-SA-3.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"CC-BY-NC-SA-3.0")) {
        _matched=true;
        _switchResult = "CC-BY-NC-SA-3.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Creative Commons Attribution Share Alike 1.0")) {
        _matched=true;
        _switchResult = "CC-BY-SA-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"CC-BY-SA-1.0")) {
        _matched=true;
        _switchResult = "CC-BY-SA-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Creative Commons Attribution Share Alike 2.0")) {
        _matched=true;
        _switchResult = "CC-BY-SA-2.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"CC-BY-SA-2.0")) {
        _matched=true;
        _switchResult = "CC-BY-SA-2.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Creative Commons Attribution Share Alike 2.5")) {
        _matched=true;
        _switchResult = "CC-BY-SA-2.5";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"CC-BY-SA-2.5")) {
        _matched=true;
        _switchResult = "CC-BY-SA-2.5";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Creative Commons Attribution Share Alike 3.0")) {
        _matched=true;
        _switchResult = "CC-BY-SA-3.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"CC-BY-SA-3.0")) {
        _matched=true;
        _switchResult = "CC-BY-SA-3.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Creative Commons Zero v1.0 Universal")) {
        _matched=true;
        _switchResult = "CC0-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"CC0-1.0")) {
        _matched=true;
        _switchResult = "CC0-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"CUA Office Public License v1.0")) {
        _matched=true;
        _switchResult = "CUA-OPL-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"CUA-OPL-1.0")) {
        _matched=true;
        _switchResult = "CUA-OPL-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Eclipse Public License 1.0")) {
        _matched=true;
        _switchResult = "EPL-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"EPL-1.0")) {
        _matched=true;
        _switchResult = "EPL-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"eCos license version 2.0")) {
        _matched=true;
        _switchResult = "eCos-2.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"eCos-2.0")) {
        _matched=true;
        _switchResult = "eCos-2.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Educational Community License v1.0")) {
        _matched=true;
        _switchResult = "ECL-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"ECL-1.0")) {
        _matched=true;
        _switchResult = "ECL-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Educational Community License v2.0")) {
        _matched=true;
        _switchResult = "ECL-2.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"ECL-2.0")) {
        _matched=true;
        _switchResult = "ECL-2.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Eiffel Forum License v1.0")) {
        _matched=true;
        _switchResult = "EFL-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"EFL-1.0")) {
        _matched=true;
        _switchResult = "EFL-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Eiffel Forum License v2.0")) {
        _matched=true;
        _switchResult = "EFL-2.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"EFL-2.0")) {
        _matched=true;
        _switchResult = "EFL-2.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Entessa Public License v1.0")) {
        _matched=true;
        _switchResult = "Entessa";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Entessa")) {
        _matched=true;
        _switchResult = "Entessa";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Erlang Public License v1.1")) {
        _matched=true;
        _switchResult = "ErlPL-1.1";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"ErlPL-1.1")) {
        _matched=true;
        _switchResult = "ErlPL-1.1";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"EU DataGrid Software License")) {
        _matched=true;
        _switchResult = "EUDatagrid";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"EUDatagrid")) {
        _matched=true;
        _switchResult = "EUDatagrid";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"European Union Public License 1.0")) {
        _matched=true;
        _switchResult = "EUPL-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"EUPL-1.0")) {
        _matched=true;
        _switchResult = "EUPL-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"European Union Public License 1.1")) {
        _matched=true;
        _switchResult = "EUPL-1.1";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"EUPL-1.1")) {
        _matched=true;
        _switchResult = "EUPL-1.1";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Fair License")) {
        _matched=true;
        _switchResult = "Fair";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Fair")) {
        _matched=true;
        _switchResult = "Fair";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Frameworx Open License 1.0")) {
        _matched=true;
        _switchResult = "Frameworx-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Frameworx-1.0")) {
        _matched=true;
        _switchResult = "Frameworx-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"GNU Affero General Public License v3.0")) {
        _matched=true;
        _switchResult = "AGPL-3.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"AGPL-3.0")) {
        _matched=true;
        _switchResult = "AGPL-3.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"GNU Free Documentation License v1.1")) {
        _matched=true;
        _switchResult = "GFDL-1.1";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"GFDL-1.1")) {
        _matched=true;
        _switchResult = "GFDL-1.1";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"GNU Free Documentation License v1.2")) {
        _matched=true;
        _switchResult = "GFDL-1.2";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"GFDL-1.2")) {
        _matched=true;
        _switchResult = "GFDL-1.2";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"GNU Free Documentation License v1.3")) {
        _matched=true;
        _switchResult = "GFDL-1.3";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"GFDL-1.3")) {
        _matched=true;
        _switchResult = "GFDL-1.3";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"GNU General Public License v1.0 only")) {
        _matched=true;
        _switchResult = "GPL-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"GPL-1.0")) {
        _matched=true;
        _switchResult = "GPL-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"GNU General Public License v1.0 or later")) {
        _matched=true;
        _switchResult = "GPL-1.0+";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"GPL-1.0+")) {
        _matched=true;
        _switchResult = "GPL-1.0+";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"GNU General Public License v2.0 only")) {
        _matched=true;
        _switchResult = "GPL-2.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"GPL-2.0")) {
        _matched=true;
        _switchResult = "GPL-2.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"GNU General Public License v2.0 or later")) {
        _matched=true;
        _switchResult = "GPL-2.0+";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"GPL-2.0+")) {
        _matched=true;
        _switchResult = "GPL-2.0+";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"GNU General Public License v2.0 w/Autoconf exception")) {
        _matched=true;
        _switchResult = "GPL-2.0-with-autoconf-exception";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"GPL-2.0-with-autoconf-exception")) {
        _matched=true;
        _switchResult = "GPL-2.0-with-autoconf-exception";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"GNU General Public License v2.0 w/Bison exception")) {
        _matched=true;
        _switchResult = "GPL-2.0-with-bison-exception";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"GPL-2.0-with-bison-exception")) {
        _matched=true;
        _switchResult = "GPL-2.0-with-bison-exception";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"GNU General Public License v2.0 w/Classpath exception")) {
        _matched=true;
        _switchResult = "GPL-2.0-with-classpath-exception";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"GPL-2.0-with-classpath-exception")) {
        _matched=true;
        _switchResult = "GPL-2.0-with-classpath-exception";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"GNU General Public License v2.0 w/Font exception")) {
        _matched=true;
        _switchResult = "GPL-2.0-with-font-exception";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"GPL-2.0-with-font-exception")) {
        _matched=true;
        _switchResult = "GPL-2.0-with-font-exception";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"GNU General Public License v2.0 w/GCC Runtime Library exception")) {
        _matched=true;
        _switchResult = "GPL-2.0-with-GCC-exception";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"GPL-2.0-with-GCC-exception")) {
        _matched=true;
        _switchResult = "GPL-2.0-with-GCC-exception";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"GNU General Public License v3.0 only")) {
        _matched=true;
        _switchResult = "GPL-3.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"GPL-3.0")) {
        _matched=true;
        _switchResult = "GPL-3.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"GNU General Public License v3.0 or later")) {
        _matched=true;
        _switchResult = "GPL-3.0+";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"GPL-3.0+")) {
        _matched=true;
        _switchResult = "GPL-3.0+";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"GNU General Public License v3.0 w/Autoconf exception")) {
        _matched=true;
        _switchResult = "GPL-3.0-with-autoconf-exception";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"GPL-3.0-with-autoconf-exception")) {
        _matched=true;
        _switchResult = "GPL-3.0-with-autoconf-exception";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"GNU General Public License v3.0 w/GCC Runtime Library exception")) {
        _matched=true;
        _switchResult = "GPL-3.0-with-GCC-exception";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"GPL-3.0-with-GCC-exception")) {
        _matched=true;
        _switchResult = "GPL-3.0-with-GCC-exception";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"GNU Lesser General Public License v2.1 only")) {
        _matched=true;
        _switchResult = "LGPL-2.1";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"LGPL-2.1")) {
        _matched=true;
        _switchResult = "LGPL-2.1";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"GNU Lesser General Public License v2.1 or later")) {
        _matched=true;
        _switchResult = "LGPL-2.1+";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"LGPL-2.1+")) {
        _matched=true;
        _switchResult = "LGPL-2.1+";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"GNU Lesser General Public License v3.0 only")) {
        _matched=true;
        _switchResult = "LGPL-3.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"LGPL-3.0")) {
        _matched=true;
        _switchResult = "LGPL-3.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"GNU Lesser General Public License v3.0 or later")) {
        _matched=true;
        _switchResult = "LGPL-3.0+";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"LGPL-3.0+")) {
        _matched=true;
        _switchResult = "LGPL-3.0+";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"GNU Library General Public License v2 only")) {
        _matched=true;
        _switchResult = "LGPL-2.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"LGPL-2.0")) {
        _matched=true;
        _switchResult = "LGPL-2.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"GNU Library General Public License v2 or later")) {
        _matched=true;
        _switchResult = "LGPL-2.0+";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"LGPL-2.0+")) {
        _matched=true;
        _switchResult = "LGPL-2.0+";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"gSOAP Public License v1.3b")) {
        _matched=true;
        _switchResult = "gSOAP-1.3b";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"gSOAP-1.3b")) {
        _matched=true;
        _switchResult = "gSOAP-1.3b";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Historic Permission Notice and Disclaimer")) {
        _matched=true;
        _switchResult = "HPND";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"HPND")) {
        _matched=true;
        _switchResult = "HPND";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"IBM Public License v1.0")) {
        _matched=true;
        _switchResult = "IPL-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"IPL-1.0")) {
        _matched=true;
        _switchResult = "IPL-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"IPA Font License")) {
        _matched=true;
        _switchResult = "IPA";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"IPA")) {
        _matched=true;
        _switchResult = "IPA";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"ISC License")) {
        _matched=true;
        _switchResult = "ISC";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"ISC")) {
        _matched=true;
        _switchResult = "ISC";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"LaTeX Project Public License v1.0")) {
        _matched=true;
        _switchResult = "LPPL-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"LPPL-1.0")) {
        _matched=true;
        _switchResult = "LPPL-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"LaTeX Project Public License v1.1")) {
        _matched=true;
        _switchResult = "LPPL-1.1";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"LPPL-1.1")) {
        _matched=true;
        _switchResult = "LPPL-1.1";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"LaTeX Project Public License v1.2")) {
        _matched=true;
        _switchResult = "LPPL-1.2";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"LPPL-1.2")) {
        _matched=true;
        _switchResult = "LPPL-1.2";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"LaTeX Project Public License v1.3c")) {
        _matched=true;
        _switchResult = "LPPL-1.3c";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"LPPL-1.3c")) {
        _matched=true;
        _switchResult = "LPPL-1.3c";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"libpng License")) {
        _matched=true;
        _switchResult = "Libpng";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Libpng")) {
        _matched=true;
        _switchResult = "Libpng";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Lucent Public License Version 1.0 (Plan9)")) {
        _matched=true;
        _switchResult = "LPL-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"LPL-1.0")) {
        _matched=true;
        _switchResult = "LPL-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Lucent Public License v1.02")) {
        _matched=true;
        _switchResult = "LPL-1.02";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"LPL-1.02")) {
        _matched=true;
        _switchResult = "LPL-1.02";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Microsoft Public License")) {
        _matched=true;
        _switchResult = "MS-PL";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"MS-PL")) {
        _matched=true;
        _switchResult = "MS-PL";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Microsoft Reciprocal License")) {
        _matched=true;
        _switchResult = "MS-RL";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"MS-RL")) {
        _matched=true;
        _switchResult = "MS-RL";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"MirOS Licence")) {
        _matched=true;
        _switchResult = "MirOS";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"MirOS")) {
        _matched=true;
        _switchResult = "MirOS";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"MIT License")) {
        _matched=true;
        _switchResult = "MIT";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"MIT")) {
        _matched=true;
        _switchResult = "MIT";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Motosoto License")) {
        _matched=true;
        _switchResult = "Motosoto";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Motosoto")) {
        _matched=true;
        _switchResult = "Motosoto";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Mozilla Public License 1.0")) {
        _matched=true;
        _switchResult = "MPL-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"MPL-1.0")) {
        _matched=true;
        _switchResult = "MPL-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Mozilla Public License 1.1")) {
        _matched=true;
        _switchResult = "MPL-1.1";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"MPL-1.1")) {
        _matched=true;
        _switchResult = "MPL-1.1";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Mozilla Public License 2.0")) {
        _matched=true;
        _switchResult = "MPL-2.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"MPL-2.0")) {
        _matched=true;
        _switchResult = "MPL-2.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Mozilla Public License 2.0 (no copyleft exception)")) {
        _matched=true;
        _switchResult = "MPL-2.0-no-copyleft-exception";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"MPL-2.0-no-copyleft-exception")) {
        _matched=true;
        _switchResult = "MPL-2.0-no-copyleft-exception";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Multics License")) {
        _matched=true;
        _switchResult = "Multics";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Multics")) {
        _matched=true;
        _switchResult = "Multics";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"NASA Open Source Agreement 1.3")) {
        _matched=true;
        _switchResult = "NASA-1.3";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"NASA-1.3")) {
        _matched=true;
        _switchResult = "NASA-1.3";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Naumen Public License")) {
        _matched=true;
        _switchResult = "Naumen";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Naumen")) {
        _matched=true;
        _switchResult = "Naumen";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Nethack General Public License")) {
        _matched=true;
        _switchResult = "NGPL";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"NGPL")) {
        _matched=true;
        _switchResult = "NGPL";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Nokia Open Source License")) {
        _matched=true;
        _switchResult = "Nokia";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Nokia")) {
        _matched=true;
        _switchResult = "Nokia";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Non-Profit Open Software License 3.0")) {
        _matched=true;
        _switchResult = "NPOSL-3.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"NPOSL-3.0")) {
        _matched=true;
        _switchResult = "NPOSL-3.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"NTP License")) {
        _matched=true;
        _switchResult = "NTP";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"NTP")) {
        _matched=true;
        _switchResult = "NTP";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"OCLC Research Public License 2.0")) {
        _matched=true;
        _switchResult = "OCLC-2.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"OCLC-2.0")) {
        _matched=true;
        _switchResult = "OCLC-2.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"ODC Open Database License v1.0")) {
        _matched=true;
        _switchResult = "ODbL-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"ODbL-1.0")) {
        _matched=true;
        _switchResult = "ODbL-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"ODC Public Domain Dedication & License 1.0")) {
        _matched=true;
        _switchResult = "PDDL-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"PDDL-1.0")) {
        _matched=true;
        _switchResult = "PDDL-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Open Group Test Suite License")) {
        _matched=true;
        _switchResult = "OGTSL";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"OGTSL")) {
        _matched=true;
        _switchResult = "OGTSL";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Open Software License 1.0")) {
        _matched=true;
        _switchResult = "OSL-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"OSL-1.0")) {
        _matched=true;
        _switchResult = "OSL-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Open Software License 2.0")) {
        _matched=true;
        _switchResult = "OSL-2.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"OSL-2.0")) {
        _matched=true;
        _switchResult = "OSL-2.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Open Software License 2.1")) {
        _matched=true;
        _switchResult = "OSL-2.1";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"OSL-2.1")) {
        _matched=true;
        _switchResult = "OSL-2.1";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Open Software License 3.0")) {
        _matched=true;
        _switchResult = "OSL-3.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"OSL-3.0")) {
        _matched=true;
        _switchResult = "OSL-3.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"OpenLDAP Public License v2.8")) {
        _matched=true;
        _switchResult = "OLDAP-2.8";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"OLDAP-2.8")) {
        _matched=true;
        _switchResult = "OLDAP-2.8";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"OpenSSL License")) {
        _matched=true;
        _switchResult = "OpenSSL";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"OpenSSL")) {
        _matched=true;
        _switchResult = "OpenSSL";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"PHP License v3.0")) {
        _matched=true;
        _switchResult = "PHP-3.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"PHP-3.0")) {
        _matched=true;
        _switchResult = "PHP-3.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"PHP LIcense v3.01")) {
        _matched=true;
        _switchResult = "PHP-3.01";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"PHP-3.01")) {
        _matched=true;
        _switchResult = "PHP-3.01";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"PostgreSQL License")) {
        _matched=true;
        _switchResult = "PostgreSQL";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"PostgreSQL")) {
        _matched=true;
        _switchResult = "PostgreSQL";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Python License 2.0")) {
        _matched=true;
        _switchResult = "Python-2.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Python-2.0")) {
        _matched=true;
        _switchResult = "Python-2.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Q Public License 1.0")) {
        _matched=true;
        _switchResult = "QPL-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"QPL-1.0")) {
        _matched=true;
        _switchResult = "QPL-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"RealNetworks Public Source License v1.0")) {
        _matched=true;
        _switchResult = "RPSL-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"RPSL-1.0")) {
        _matched=true;
        _switchResult = "RPSL-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Reciprocal Public License 1.5")) {
        _matched=true;
        _switchResult = "RPL-1.5";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"RPL-1.5")) {
        _matched=true;
        _switchResult = "RPL-1.5";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Red Hat eCos Public License v1.1")) {
        _matched=true;
        _switchResult = "RHeCos-1.1";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"RHeCos-1.1")) {
        _matched=true;
        _switchResult = "RHeCos-1.1";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Ricoh Source Code Public License")) {
        _matched=true;
        _switchResult = "RSCPL";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"RSCPL")) {
        _matched=true;
        _switchResult = "RSCPL";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Ruby License")) {
        _matched=true;
        _switchResult = "Ruby";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Ruby")) {
        _matched=true;
        _switchResult = "Ruby";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Sax Public Domain Notice")) {
        _matched=true;
        _switchResult = "SAX-PD";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"SAX-PD")) {
        _matched=true;
        _switchResult = "SAX-PD";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"SIL Open Font License 1.0")) {
        _matched=true;
        _switchResult = "OFL-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"OFL-1.0")) {
        _matched=true;
        _switchResult = "OFL-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"SIL Open Font License 1.1")) {
        _matched=true;
        _switchResult = "OFL-1.1";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"OFL-1.1")) {
        _matched=true;
        _switchResult = "OFL-1.1";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Simple Public License 2.0")) {
        _matched=true;
        _switchResult = "SimPL-2.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"SimPL-2.0")) {
        _matched=true;
        _switchResult = "SimPL-2.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Sleepycat License")) {
        _matched=true;
        _switchResult = "Sleepycat";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Sleepycat")) {
        _matched=true;
        _switchResult = "Sleepycat";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"SugarCRM Public License v1.1.3")) {
        _matched=true;
        _switchResult = "SugarCRM-1.1.3";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"SugarCRM-1.1.3")) {
        _matched=true;
        _switchResult = "SugarCRM-1.1.3";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Sun Public License v1.0")) {
        _matched=true;
        _switchResult = "SPL-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"SPL-1.0")) {
        _matched=true;
        _switchResult = "SPL-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Sybase Open Watcom Public License 1.0")) {
        _matched=true;
        _switchResult = "Watcom-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Watcom-1.0")) {
        _matched=true;
        _switchResult = "Watcom-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"University of Illinois/NCSA Open Source License")) {
        _matched=true;
        _switchResult = "NCSA";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"NCSA")) {
        _matched=true;
        _switchResult = "NCSA";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Vovida Software License v1.0")) {
        _matched=true;
        _switchResult = "VSL-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"VSL-1.0")) {
        _matched=true;
        _switchResult = "VSL-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"W3C Software and Notice License")) {
        _matched=true;
        _switchResult = "W3C";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"W3C")) {
        _matched=true;
        _switchResult = "W3C";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"wxWindows Library License")) {
        _matched=true;
        _switchResult = "WXwindows";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"WXwindows")) {
        _matched=true;
        _switchResult = "WXwindows";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"X.Net License")) {
        _matched=true;
        _switchResult = "Xnet";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Xnet")) {
        _matched=true;
        _switchResult = "Xnet";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"XFree86 License 1.1")) {
        _matched=true;
        _switchResult = "XFree86-1.1";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"XFree86-1.1")) {
        _matched=true;
        _switchResult = "XFree86-1.1";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Yahoo! Public License v1.0")) {
        _matched=true;
        _switchResult = "YPL-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"YPL-1.0")) {
        _matched=true;
        _switchResult = "YPL-1.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Yahoo! Public License v1.1")) {
        _matched=true;
        _switchResult = "YPL-1.1";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"YPL-1.1")) {
        _matched=true;
        _switchResult = "YPL-1.1";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Zimbra Public License v1.3")) {
        _matched=true;
        _switchResult = "Zimbra-1.3";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Zimbra-1.3")) {
        _matched=true;
        _switchResult = "Zimbra-1.3";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"zlib License")) {
        _matched=true;
        _switchResult = "Zlib";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Zlib")) {
        _matched=true;
        _switchResult = "Zlib";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Zope Public License 1.1")) {
        _matched=true;
        _switchResult = "ZPL-1.1";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"ZPL-1.1")) {
        _matched=true;
        _switchResult = "ZPL-1.1";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Zope Public License 2.0")) {
        _matched=true;
        _switchResult = "ZPL-2.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"ZPL-2.0")) {
        _matched=true;
        _switchResult = "ZPL-2.0";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"Zope Public License 2.1")) {
        _matched=true;
        _switchResult = "ZPL-2.1";
      }
    }
    if (!_matched) {
      if (Objects.equal(getLicense,"ZPL-2.1")) {
        _matched=true;
        _switchResult = "ZPL-2.1";
      }
    }
    if (!_matched) {
      _switchResult = "LGPL-3.0+";
    }
    return _switchResult;
  }
}
